### ISSUE TITLE
[Idea] Switch the top image of the README according to the LIGHT/DARK mode.

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2023#1032]
**Idea Description**
- I thought it would be interesting to switch the top image using [this feature](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) of Markdown.
- A dark mode version of the top image in the README can be reflected immediately when available.

**Reference images and links**

The image below switches display depending on the terminal's LIGHT/DARK mode.

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/DroidKaigi/conference-app-2023/main/feature/about/src/main/res/drawable-night-xxhdpi/img_about_key_visual.webp">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/DroidKaigi/conference-app-2023/main/feature/about/src/main/res/drawable-xxhdpi/img_about_key_visual.webp">
  <img alt="Shows an illustrated sun in light mode and a moon with stars in dark mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>

**Comment by takahirom** [comment]
I didn't know this! Looks awesome!

**Comment by Corvus400** [comment]
If the designer has extra resources and can provide images, we would like to reflect this!🙋

**Comment by takahirom** [comment]
Do you mean we need a copyright in the image?

**Comment by Corvus400** [comment]
Yes!
It means you need a dark mode version of [this image.](https://github-production-user-asset-6210df.s3.amazonaws.com/1386930/260435272-22efb1a7-5a43-469c-a493-fa619034863e.png)
![image](https://github.com/DroidKaigi/conference-app-2023/assets/13657682/0388e4b9-eb39-4dc7-b7dc-15a773299007)

**Comment by nobonobopurin** [comment]
@Corvus400  I've prepared images for the dark mode. Please use this one.
![Google Play Feature Graphic-dark](https://github.com/DroidKaigi/conference-app-2023/assets/136104152/ae2b1067-966f-47a2-aa10-4e1ee4d09418)

**Comment by Corvus400** [comment]
@nobonobopurin @takahirom 
Thank you!
However, it seems that I am currently getting the images from AWS.
Is it safe to refer to them in the form of placing them in the docs/img directory of the repository?
