### ISSUE TITLE
Navigation bar color not set when using 3-button navigation

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#1048]
**Describe the bug**
Navigation bar color not set when using 3-button navigation

**To Reproduce**
1. Launch this app

**Expected behavior**
The color of the 3-button navigation is the same as the `KaigiBottomBar` container color.

**Screenshots**
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/ef27c846-1fa2-42c1-9f70-47e19f49b607" width="300">

## What I know at this time
The following will fix the problem for API28 and other devices, but if the device switches between gesture navigation and 3-button navigation in the settings, the color of the 3-button navigation will not be displayed.

https://github.com/DroidKaigi/conference-app-2023/blob/0fb3c4d81e1deb4bd976cded6601977ad20efc01/app-android/src/main/java/io/github/droidkaigi/confsched2023/MainActivity.kt#L26

 ↓ ↓ ↓ ↓ ↓

```
enableEdgeToEdge(
    statusBarStyle = SystemBarStyle.auto(
        lightScrim = Color.Transparent.toArgb(),
        darkScrim = Color.Transparent.toArgb(),
    ),
    navigationBarStyle = SystemBarStyle.auto(
        lightScrim = Color.Transparent.toArgb(),
        darkScrim = Color.Transparent.toArgb(),
    ),
)

```
|Before|After|Description|
|---|---|---|
|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/d24740fc-4042-4c6c-83d3-0ff7df77b10d" width="300">|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/aca812c1-1a4f-4f43-9863-21dc7fb5e69f" width="300">|Emulator Pixel4 API28 (Only 3-button navigation  can be configured.)|
|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/b3e915ca-018d-45e8-b4aa-e140b8b20beb" width="300">|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/4ff6a9e9-62a2-49fb-b911-fe8825ac43d9" width="300">|Emulator Pixel6 API30 3-buttonNavigation|
|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/81f0c196-2e9f-4535-a60a-ceffdb8cbacd" width="300">|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/ea76b699-0145-4090-bfea-83fdf9f8f182" width="300">|Emulator Pixel6 API30 GestureNavigation|

**Comment by takahirom** [comment]
Looks great!

**Comment by takahirom** [comment]
@kosenda 
Do you want to do this?

**Comment by kosenda** [comment]
@takahirom 
Thank you !
In conclusion, I wouldn't want todo this issue. 
Because I had been trying various ways to do this, but on a device that allows both 3-button navigation and gesture navigation, I have no idea how to set the color for the 3-button navigation at the moment.

**Comment by takahirom** [comment]
@kosenda What if we add a comment saying we have problem and just add a fix for API 28?

**Comment by kosenda** [comment]
@takahirom If those are the only two things I would like to do !

**Comment by takahirom** [comment]
@kosenda I'll leave this issue as it is not solved but you can do it whenever you want!

**Comment by kosenda** [comment]
@takahirom I understand !

**Comment by ked4ma** [comment]
Sorry for jumping in from the side. :pray: 
I tried specifying `containerColor = Color.Red` for `KaigiBottomBar`, 
and it seemed like the navbar indeed displayed a faint ping color (as seen in the left image). 
Also, during the dark theme, it seemed like the contrast was adjusted (as shown in the right image). 
The settings seem to be applied correctly, but maybe the contrast made it barely noticeable.
(I tryed with "Pixel 6 API 30")

| light | dark |
| :--: | :--: |
| <img src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/d66515b3-ea11-4704-aceb-9e4d511c669b" width="300" /> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/5f6bf49d-65ec-4f76-871e-b2e11e8443a3" width="300" /> |

**Comment by kosenda** [comment]
Thank you !
It was very helpful to have the color settings themselves!

**Comment by nkratochwill** [comment]
This should color the statusbar and 3 button navigation bar correctly on all android versions in both light and dark mode:
```
val currentNightMode = resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
val systemBarStyle = when (currentNightMode) {
    Configuration.UI_MODE_NIGHT_NO -> SystemBarStyle.light(Color.Transparent.toArgb(), Color.Transparent.toArgb())
    Configuration.UI_MODE_NIGHT_YES -> SystemBarStyle.dark(Color.Transparent.toArgb())
    else -> error("Illegal State, current mode is $currentNightMode")
}
enableEdgeToEdge(
    statusBarStyle = systemBarStyle,
    navigationBarStyle = systemBarStyle,
)
```
Cheers
