### ISSUE TITLE
Haptic feedback for session bookmarking

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1056]
**Idea Description**
Haptic feedback for session bookmarking is an idea from the designer. It might be a great feature, but I don't want it to become annoying. Can we implement it in a subtle way?

**Reference images and links**

**Comment by kosenda** [comment]
I would like to do!

**Comment by fumiya-kume** [comment]
I want to do it as well! 
@kosenda  Can we sync and split the implementation points?

**Comment by kosenda** [comment]
@fumiya-kume 
I wanted to do it if there was someone who wanted to do it,
so if you does it, it doesn't matter if I am not in charge 🙇

**Comment by takahirom** [comment]
Sorry for being late. We are so busy and it makes it difficult to manage issues like this. 🙇 
@kosenda I didn't assign but I think you arise a hand first so you think you can make a pr.

**Comment by kosenda** [comment]
@takahirom  Thank you 🙇
I wound't mind if I don't work on it, because @Nanamare is working it.

**Comment by takahirom** [comment]
OK. Thanks. Sorry for being late 🙇

**Comment by Nanamare** [comment]
@kosenda Thank you for your consideration 🙇‍♂️
