### ISSUE TITLE
[Compose Multiplatform iOS]Apply the app's theme explicitly by adding KaigiTheme at the root of ContributorsScreen to change colors in this content

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1062]
**Idea Description**
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/c2737d80-9db3-4cb1-bbd0-be53809bd445)

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/pull/1054#issuecomment-1703973359

**Comment by ttanaka330** [comment]
Can i try this issue?

**Comment by takahirom** [comment]
@ttanaka330 Thanks! Assigned 👍 
I just confirm that this may involve iOS app build. Is it ok?

**Comment by ttanaka330** [comment]
@takahirom 
Sorry, I just cannot confirm that this may involve iOS app build.

**Comment by takahirom** [comment]
@ttanaka330 It's ok! Thanks! I've edited the title 🙏

**Comment by tkhs0604** [comment]
📝 KaigiTheme refers to the custom font file, so the following error occurs when just wrapping ContributesScreen by KaigiTheme:
> Uncaught Kotlin exception: kotlin.IllegalArgumentException: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: font/montserrat_medium.ttf

If KaigiTheme does not refer to any font files, that is, the default font is used, it seems to work well.
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/35547fe2-82e9-42a1-abce-4bfd0e938ebd" width="300">
