### ISSUE TITLE
Empty tags may appear in BookmarkList and SearchList (in code)

### ISSUE THREAD

**Issue by kkkkan** [DroidKaigi/conference-app-2023#1069]
**Idea Description**
Empty tags may appear in BookmarkList and SearchList (in code)
**Reference images and links**
In the process of creating tags for each item in the bookmark list and search results list, we are adding an empty tag if `timetableItem.day?.name` is null. This has led to the possibility of empty string tags being created and displayed in the code.

- in BookmarkList
https://github.com/DroidKaigi/conference-app-2023/blob/8ac1aa8273440566cc20665d8e6dfe4e3cda3eef/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/BookmarkList.kt#L119

- in SearchList
https://github.com/DroidKaigi/conference-app-2023/blob/8ac1aa8273440566cc20665d8e6dfe4e3cda3eef/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/SearchList.kt#L141

Due to the nature of the product, it is unlikely that `timetableItem.day?.name` would be null. Instead of using `timetableItem.day?.name.orEmpty()`, I believe it would be more appropriate to use `timetableItem.day?.name!!` or only create the tag if `timetableItem.day?.name` is not null.

**Comment by kkkkan** [comment]
🙋 (But it probably conflicts with https://github.com/DroidKaigi/conference-app-2023/pull/1067, so I would like to start when this is merged if allowed.)

**Comment by tkhs0604** [comment]
@kkkkan 
Your PR has been merged just now, so let me assign you!
