### ISSUE TITLE
[iOS] TimetableView's toolbar items are disappeared on Dark mode

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#1076]
**Describe the bug**
Title says all.

**To Reproduce**
1. Set device scheme to Dark mode
2. Open iOS App 
3. Open TimetableView
4. See this issue

**Expected behavior**
ToolbarItems are appeared in Dark mode as well.

**Screenshots**

Light|Dark
--|--
<img width="506" alt="スクリーンショット 2023-09-04 3 16 27" src="https://github.com/DroidKaigi/conference-app-2023/assets/30540303/e58f39de-b18b-4974-b01b-d3a37dbd2781">|<img width="506" alt="スクリーンショット 2023-09-04 3 16 20" src="https://github.com/DroidKaigi/conference-app-2023/assets/30540303/e3af97b5-d046-433f-84f8-0886e832accd">

**Comment by saikei718** [comment]
🤚
