### ISSUE TITLE
[Android] App crashes on sponsor screen when network is offline

### ISSUE THREAD

**Issue by koji-1009** [DroidKaigi/conference-app-2023#1092]
**Describe the bug**
The app crashes when opening the sponsor screen for the first time after launching the app while offline.

**To Reproduce**
1. Go to 'About screen'
2. Set 'Airplane mode'
3. Click on 'Sponsor'

**Expected behavior**
App should not crash, and instead show some error.

**Screenshots**

<video src="https://github.com/DroidKaigi/conference-app-2023/assets/17231507/dece8233-aa29-48b9-8651-11aeef543f2f" width="300">

**Similar issue**

#950

**Comment by takahirom** [comment]
Oh, really? Thanks!

**Comment by ked4ma** [comment]
I want to try fixing this 🖐

**Comment by RyuNen344** [comment]
Thank you~~! assigned!
