### ISSUE TITLE
[Android] Snackbar padding is different with other screens on timetable

### ISSUE THREAD

**Issue by ked4ma** [DroidKaigi/conference-app-2023#1098]
**Idea Description**
Paddings of snackbar on timetable screen is different with other screens
(session detail, contributors, etc...)
I felt it is little bit wierd :thinking: 

**Reference images and links**
timetable | session detail | contributor
:--: | :--: | :--:
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/fef1e985-6833-4017-be9b-9d4b4d317347" width="200" /> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/d63ee0dc-4191-4cb8-9597-5f432192bea2" width="200" /> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/e2b92af2-8316-4058-a3a4-a71ebc7d2ebc" width="200" />

**Comment by ked4ma** [comment]
If it's ok to fit paddings with other screen, I'll do it :raised_hand_with_fingers_splayed: 

(Is it a bug error message is not shown??? :thinking: )

**Comment by takahirom** [comment]
I wonder why AppError.mesagge is null but thanks!
