### ISSUE TITLE
Snackbar's message isn't shown

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1101]
**Describe the bug**
We can't see the snack bar message

**To Reproduce**
1. Enable air plain mode
2. Go to contributor screen
3. See empty snackbar 

**Expected behavior**
You can see the message

**Screenshots**
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/cb1ecf6b-83c9-4b34-8fa5-b35c39452935)

**Comment by ked4ma** [comment]
I also want to do this :raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
@ked4ma I'm looking forward to your implementation!
