### ISSUE TITLE
[Android] Unpredictable Timetable App Bar Bookmark Icon State

### ISSUE THREAD

**Issue by ohzono** [DroidKaigi/conference-app-2023#1116]
**Describe the bug**
Reproduced with an app released from the Play Store.
The state of the bookmark icon in the top app bar resets upon restarting the app. I'm not sure if this is the intended behavior or a bug.

**To Reproduce**
Follow these steps to reproduce the behavior:

1. Verify the visibility of the bookmark list icon in the top app bar.
2. Tap the 'bookmark icon' found on the timetable within a session item.
3. Observe that the bookmark list icon in the top app bar changes (it fills with color and a '+' appears on the icon).
4. Restart the app.
5. Notice that the bookmark list icon in the top app bar reverts to its state from step 2.

Sometimes didn't happen, but you can see the other pattern's state management problems.

**Expected behavior**
In this scenario, the state of the bookmark list icon in the top app bar should not change when the app is restarted.

**Screenshots**

I will attach the recorded one later. 🙏

**Comment by takahirom** [comment]
It seems bug! Thanks!

**Comment by ked4ma** [comment]
It seems little bit complecated (arround state updating timing), but I want to try this issue! :raised_hand_with_fingers_splayed:
