### ISSUE TITLE
[iOS] AchievementRepository dependency not provided

### ISSUE THREAD

**Issue by iiinaiii** [DroidKaigi/conference-app-2023#1122]
**Describe the bug**
When I start the application, I get the following error.

```
Uncaught Kotlin exception: org.koin.core.error.NoBeanDefFoundException: No definition found for 
class:'io.github.droidkaigi.confsched2023. AchievementRepository' q:''. Check your definitions!
```

iOSMain > io.github.droidkaigi.confsched2023.data.DataModule.kt does not contain AchievementRepository dependency.

**To Reproduce**
1. Start up application
2. The error happen

**Expected behavior**
The application should start up properly.

**Screenshots**

**Comment by tkhs0604** [comment]
Thank you for your report! It must be resolved by this PR 🙆‍♂️ https://github.com/DroidKaigi/conference-app-2023/pull/1141
