### ISSUE TITLE
Update floor map

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1130]
**Idea Description**
The floor map on figma was updated. So please apply it!

**Reference images and links**

**Comment by ked4ma** [comment]
I viewed figma :eyes: 
Is it correct that this issue is to update floor image??
If so, i'll do this if there isn't other person want to do. :raised_back_of_hand:

**Comment by momomomo111** [comment]
@ked4ma 
It would be great if you could update the floor map based on Figma's information!
Thanks! Assigned!
