### ISSUE TITLE
[iOS] Use the defined Typography on each screen.

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2023#1144]
## Summary

- Use the Typography implemented in task #889 on each screen.

**Comment by Corvus400** [comment]
@ry-itto @tkhs0604 
I would like to do this task.🙋

**Comment by Corvus400** [comment]
Before we do this task, do we also need to do a task to combine each of the prepared theme files into a file like Theme.kt and provide it as a theme? 🤔

**Comment by momomomo111** [comment]
@Corvus400 
I don't know about the iOS details, but I have assigned them. Thanks for working on it.

**Comment by ry-itto** [comment]
@Corvus400 
It seems to be a Xcode Beta problem 🙏🏼 

>  As for the PreviewProvider issue sounds like a separate and not tracked issue.
> https://developer.apple.com/forums/thread/731887

**Comment by ry-itto** [comment]
Sorry... Please check that with builded app 🙏🏼
