### ISSUE TITLE
Hide text when enable the BigFont/BigDisplay in AchievementScreenDialog

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#1147]
**Describe the bug**
Hide text when enable the BigFont/BigDisplay in AchievementScreenDialog
And scrolling is not possible.

**To Reproduce**
1. Enable BigFont/BigDisplay
2. First transition to `AchievementsScreen` after installing the app.

**Expected behavior**
All text in the dialog should be visible even if BigFont/BigDisplay is enabled.

**Screenshots**
Pixel 7 Pro API 34 (Emulator)
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/cc907619-17f2-49a7-9be4-125bf6bb36bb" width="350">

**Comment by mthiroshi** [comment]
I will try this task.🙋

**Comment by momomomo111** [comment]
@mthiroshi 
Thanks! Assigned!
