### ISSUE TITLE
[iOS] Fix contents and their order to align with Android

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#1165]
The contents and their order displayed on each tab are different from Android's ones.
They should be aligned with Android.
Bookmark and search screens could be the same situation.

&nbsp; | iOS | Android
:--: | :--: | :--:
Day1. | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/418a9526-3540-4a3e-b42f-35b9dbab4925" width="300"> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/3d99914f-41e7-4678-b845-cb52434bf8da" width="300">
Day.2 | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/27932e7c-1235-4d69-bbdd-394331efe029" width="300"> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/2ec9d8d0-d579-4c61-a298-c019e2695784" width="300"> 
Day.3 | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/dc4acb07-491f-46ee-9f09-c9453f2092b7" width="300"> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/c9a7e842-5a72-46be-b486-396bb0fed459" width="300">

**Comment by fumiyasac** [comment]
🤚

**Comment by tkhs0604** [comment]
@fumiyasac 
Thank you so much 😭 Assigned!

**Comment by fumiyasac** [comment]
@sohichiro 
Oh~, Thanks a lot. 

@tkhs0604 
If possible assignee changes from me to sohichiro.
