### ISSUE TITLE
We can't see the bottom of the sessions on day 2 grid screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1208]
**Idea Description**
How about adding space or something?

**Reference images and links**

<img width=400 src=https://github.com/DroidKaigi/conference-app-2023/assets/1386930/dc907dd2-dde9-497e-8019-3ae2046028c9 />

**Comment by Corvus400** [comment]
I'd like to try the task.🙋
Response will be quite slow since it's during Droidkaigi...🙇‍♂️

**Comment by tkhs0604** [comment]
@Corvus400 
Wow, thank you for trying this issue too!
Let's enjoy the DroidKaigi 2023 😉

**Comment by Corvus400** [comment]
@tkhs0604 @takahirom 
Whether the modifications are beautiful or not, for now, the above PR has put in place modifications that will not cause problems when you use it tomorrow. 🙇
