### ISSUE TITLE
Adjusting Time Settings to "Day 1" for Screenshot Tests

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1219]
**Idea Description**
In the current implementation of our screenshot tests, the time settings are automatically set to "Day 2." This has resulted in some inconsistencies in the test outcomes. The purpose of this document is to outline the steps required to adjust the time settings to "Day 1" for more accurate and consistent screenshot tests.

**Reference images and links**

**Comment by kubode** [comment]
🤚 
I'll try this.

**Comment by takahirom** [comment]
@kubode Thanks. But there is a pr that trying this. It seems that it doesn't work though 👀 
https://github.com/DroidKaigi/conference-app-2023/pull/1224

**Comment by kubode** [comment]
Thanks! That PR looks good 👏
