### ISSUE TITLE
Rename generateMetricsReport to generateComposeMetricsReport

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1222]
**Idea Description**
`generateMetricsReport` is a little confusing. Could you rename it?

**Reference images and links**

Please see .run/generateComposeCompilerMetricsReports.run.xml
<img width="476" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/c360d22e-d8ee-4116-bd1d-45b32ebd2db4">

**Comment by sanao1006** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
