### ISSUE TITLE
Time Display on TimetableGrid is Off by One Hour

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1226]
**Idea Description**
The time displayed on the TimetableGrid is one hour behind the actual scheduled time.

![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/2231fdb0-f269-4815-8524-dcb15bb02b8f)

For now, we released a hotfix veresion that we remove the time as 1.6.1.

![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/f8723b9e-72fd-4a32-9350-10aaac8ff6f1)

**Reference images and links**

**Comment by aqua-ix** [comment]
🙋

**Comment by tkhs0604** [comment]
Thank you for your help! Assigned!

**Comment by aqua-ix** [comment]
There may be a problem in calculating the values below.

https://github.com/DroidKaigi/conference-app-2023/blob/e52ff00429ff30d1b58433f74b20cef83763e7c7/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableGrid.kt#L360

**Comment by aqua-ix** [comment]
> It's possible that dayStart always needs to be set to 10:00(JST).

It seems to be correct, so I'll try implementing it.

**Comment by takahirom** [comment]
Thanks
