### ISSUE TITLE
Electric eel is a little bigger on Achievements screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1237]
**Idea Description**
The title says everything

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/dc337cb9-4658-4015-8db7-fb38f5aba1e0)

**Comment by gy6543721** [comment]
👀

**Comment by takahirom** [comment]
@gy6543721 Do you want to do this? Anyway assigned

**Comment by gy6543721** [comment]
[takahirom](https://github.com/takahirom) May I ask which device is the screenshot ?

**Comment by takahirom** [comment]
@gy6543721 He said it is Pixel6!

**Comment by gy6543721** [comment]
> @gy6543721 He said it is Pixel6!

Thank you for the kind reply!

Already checked that it looks fine on Pixel 6 as well 🙏🏻
