### ISSUE TITLE
Log http connection only if debug build

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1238]
**Idea Description**
https://github.com/DroidKaigi/conference-app-2023/blob/ff987f31553ffd031ad81bebc7d24132d2e1c765/core/data/src/androidMain/kotlin/io/github/droidkaigi/confsched2023/data/di/ApiModule.kt#L55

**Reference images and links**

**Comment by GGBBB2000** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
