### ISSUE TITLE
Add StaffScreenTest.checkLaunchServerErrorShot()

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1246]
**Idea Description**
It is like TimetableScreenTest.checkLaunchServerErrorShot
https://github.com/DroidKaigi/conference-app-2023/blob/b4fc2206ea95ecd9cb50380340e32b5756588f07/feature/sessions/src/test/java/io/github/droidkaigi/confsched2023/sessions/TimetableScreenTest.kt#L45

https://github.com/DroidKaigi/conference-app-2023/blob/4e592d43303334fbd46757f144b777cb03c24c03/feature/staff/src/test/java/io/github/droidkaigi/confsched2023/StaffScreenTest.kt#L25

**Reference images and links**

**Comment by Oxypetalum7** [comment]
🙋

**Comment by upon0426** [comment]
Thanks! Assigned!
