### ISSUE TITLE
Fade favorite animation end

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#1254]
**Idea Description**

[Screen_recording_20230916_144435.webm](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/fa3dc6fd-74b9-458e-a768-eacf22ab390d)

I'm not sure about this. But it may be good to animate when the bookmark animation finishes. Could you try it?

**Reference images and links**

**Comment by kosenda** [comment]
I would like to work on it 🙋

**Comment by takahirom** [comment]
Thanks!
