### ISSUE TITLE
[Build] Consiter introducing DeteKt for Linter

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2023#177]
LinterとしてDetektを検討してもいいのかも。(KtLintはフォーマッターとしてだけ使う)

ビルドエラーにしてPR書く人になおしていただく？（でも、コントリビュートが煩わしくなりそう）

PRへのコメント自体は下記が参考になりそう（detektでlintエラー検知したよ、ぐらいになるかもしれないけど）

https://github.com/DroidKaigi/conference-app-2023/pull/50/files

**Comment by matsumo0922** [comment]
Is this issue still open?
I would like to use detekt as a linter if possible.

I can also create a PR, so if it is valid, please assign yourself to it~

**Comment by tomoya0x00** [comment]
@matsumo0922
Thx for asking.
Yeah, this issue is still open.

Assigned!
