### ISSUE TITLE
Consider a logic to hide time in TimetableListItem

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#244]
As only time should be appear once for groups of sessions happens at the same time, need to implement logic for that.

<img width="437" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/03bf77f4-512b-4277-816e-d10d806d806a">

**Comment by kumokumot** [comment]
🙋 I want to try the sticky header approach.

**Comment by takahirom** [comment]
Let me close this as this is duplicated issue🙇
https://github.com/DroidKaigi/conference-app-2023/issues/383
