### ISSUE TITLE
Improve Performance by Refactoring Kotlin BookmarkScreen's ViewModel binding codes

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#269]
The current implementation of the onClickBookmarkIcon in Kotlin is onClickBookmarkIcon = { viewModel.updateBookmark(it) }. To improve performance, let's refactor it to onClickBookmarkIcon = viewModel::updateBookmark. 

https://github.com/DroidKaigi/conference-app-2023/blob/4b3e70dc82e7604ea7ec68f0ebcbb207201d1c3d/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/BookmarkScreen.kt#L55-L59

**Comment by takahirom** [comment]
@mtnmr It's been three weeks. Please let me unassign this for other contributors 🙇

**Comment by Gazyu** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned!
