### ISSUE TITLE
Remove constraintlayout-compose for Kotlin Multiplatform Compatibility

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#270]
Currently, constraintlayout-compose is not compatible with Kotlin Multiplatform, which is causing some issues in our project. One of the affected areas is BookmarkSheet. We need to remove constraintlayout-compose to maintain our project's compatibility with Kotlin Multiplatform.

**Comment by fornewid** [comment]
🙋‍♂️

**Comment by upon0426** [comment]
Thanks! Assigned you!
