### ISSUE TITLE
Create Dedicated UiState for BookmarkSheet

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#272]
Currently, we are passing Screen's UiState to BookmarkSheet, which might not be the best approach. We need to create a separate UiState for BookmarkSheet to better encapsulate its state. Please check the project's Screen section for more details: https://github.com/DroidKaigi/conference-app-2023#screen .

**Comment by YusukeSuzuki1213** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned!
