### ISSUE TITLE
Use Icons.Filled.Bookmark by Copying from androidx.compose.material:material-icons-extended

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#274]
To use Icons.Filled.Bookmark, we suggest copying it from androidx.compose.material:material-icons-extended. The reason behind this is to avoid the large binary size of material-icons-extended which could potentially slow down debugging. Please ensure to leave a comment in the code mentioning that it was copied from androidx.compose.material:material-icons-extended.

**Comment by maxfie1d** [comment]
Can I try this one?

**Comment by upon0426** [comment]
Thanks! Assigned!

**Comment by takahirom** [comment]
@maxfie1d Oh, This looks old issue. We are using icons-extended. So if you find xml vector drawable, please rewrite it to icons-extended🙇
