### ISSUE TITLE
Update BookmarkSheet EmptyView Colors to Use Theme Colors

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#275]
The EmptyView in BookmarkSheet currently uses hardcoded colors: Color(0xFFCEE9DB), Color(0xFF191C1A), and Color(0xFF404944). We should update these to use theme colors instead to maintain consistency across the application and ease of future color changes.

**Comment by okuzawats** [comment]
I understood what the issue is.
Please assign this issue to me🙋
I'll work on it later.

**Comment by takahirom** [comment]
Thanks!

**Comment by okuzawats** [comment]
@takahirom 
I thought I could fixed this issue in #532 , but I feel that the PR handle two different problems.
I'm willing to abort some changes in the PR if the reviewer requested.
Thank you.
