### ISSUE TITLE
Update BookmarkFilters Colors to Use Theme Colors

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#276]
BookmarkFilters is currently using the hardcoded color Color(0xFFCEE9DB). To maintain a consistent look and feel across our application and simplify future color updates, we should replace this hardcoded color with a corresponding color from our theme.

https://github.com/DroidKaigi/conference-app-2023/blob/main/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkFilters.kt

**Comment by Pluu** [comment]
🙋

Are the specifications to match the color of the timetable?
I also have a question about other color specifications.
Can we also fix problems that do not go through material themes like "md_theme_light_outline"?

**Comment by takahirom** [comment]
Oh you! It's been a while!
I think it is just outdated. Please update!
