### ISSUE TITLE
Update BookmarkTopArea Colors to Use Theme Colors

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#277]
BookmarkTopArea currently uses the hardcoded colors Color(0xFFF8FAF6) and Color(0xFFCEE9DB). We should update these colors to use our theme colors for consistency across our app and to simplify future color changes.

https://github.com/DroidKaigi/conference-app-2023/blob/main/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkTopArea.kt

**Comment by tfandkusu** [comment]
🙋

**Comment by RyuNen344** [comment]
thx!! asssigned!
