### ISSUE TITLE
Rename TimetableItemDetailFooter to TimetableItemDetailBottomAppBar

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#285]
The current name of TimetableItemDetailFooter might be confusing as it doesn't adequately reflect its purpose and functionality. Let's rename it to TimetableItemDetailBottomAppBar for clarity and better understanding of its role in the application.

**Comment by okuzawats** [comment]
@takahirom I fix this issue in #522. Please check the PR🙇‍♂️
