### ISSUE TITLE
Modify the design of the icons in the card section on the timetable detail screen.

### ISSUE THREAD

**Issue by swimmy-reo** [DroidKaigi/conference-app-2023#319]
## Summary 
Modify the design of the icons in the card section

## Why
In the detail screen of the timetable item, there is a difference between the card component in the overview section and the design in Figma, which should be resolved.

| current situation | ideal situation |
| ---- | ---- |
| <img width="300" alt="image" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/246bfce8-522c-4ef7-91aa-abcaf942079f"> |<img width="300" alt="image" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/13344ad8-024e-4021-8361-573a0bc7869c"> |

## Goal
- [ ] Icon tint colors are different, change to appropriate color
- [ ] wording tint colors are different, change to appropriate color
- [ ] Change the background color of the card components to the appropriate color because they are different

## Reference
feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableItemDetailContent.kt

[Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54902-39762&mode=design&t=8E9hM0o5yKWdKDoQ-4)

**Comment by WonJoongLee** [comment]
I would like to try this issue!

**Comment by takahirom** [comment]
Thanks! Assigned
