### ISSUE TITLE
Use R.drawable.xxx instead of drawable.xxx.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#321]
Conventionally we use **R.**drawable.icon_droidkaigi_logo instead of drawable.icon_droidkaigi_logo 👀 

https://github.com/DroidKaigi/conference-app-2023/blob/60a93606c112e33fceb528c9783ca40749353fcd/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableTopArea.kt#L37

https://github.com/DroidKaigi/conference-app-2023/blob/86a24f19f202d7dec2d145b165182c90c7226585/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableTopArea.kt#L37

**Comment by fucchi-senpai** [comment]
I would like to take this one 🙋

**Comment by takahirom** [comment]
Thanks!
