### ISSUE TITLE
Apply stamps initial dialog

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#331]
We would like you to implement a dialog with a warning only the first time when we transition to the stamps screen

[Figma link](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55510-60156&mode=dev)

**Comment by chankiri91** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned!

**Comment by momomomo111** [comment]
@chankiri91 
https://github.com/DroidKaigi/conference-app-2023/pull/513
We've implemented the screen transition to 'Stamps' in this PR. We would appreciate it if you could merge it into the main branch at your earliest convenience. 🙏

**Comment by takahirom** [comment]
@chankiri91 I hope all is going well. Would you have some time to update me on how this issue is progressing?

**Comment by Corvus400** [comment]
@chankiri91 @takahirom 
If it seems difficult to complete the task, I would like to receive this task myself.🙋

**Comment by takahirom** [comment]
@Corvus400 If @chankiri91 gives up or doesn't answer today, could you do it? 🙏

**Comment by Corvus400** [comment]
@takahirom 
Of course you can trust me!💪

**Comment by chankiri91** [comment]
@takahirom @Corvus400 
Thank you for your concern but I would like to try this.
To warn only the first time when we transition to the stamps screen, I create dataStore DAO and save a frag to dataStore.
If there are better solutions, could you teach me?🙇‍♂️

**Comment by Corvus400** [comment]
@chankiri91 @takahirom 
I was just about to implement it myself as shown in the screenshot.
I noticed after doing it myself that this task is not so easy.😅
<img width="530" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/4af5b0fd-e76f-4db4-abbc-b6e9dda2c98e">
<img width="296" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/5b6ae5b9-005e-4878-b876-920b53c461e7">

**Comment by Corvus400** [comment]
In the meantime, I have completed the implementation on my end.
However, since you said that you will do it on your own, I will refrain from issuing a PR containing my work once I have done it.🫡

**Comment by chankiri91** [comment]
@Corvus400 
Thank you so much. I will use that as a reference!🙇‍♂️

**Comment by Corvus400** [comment]
@chankiri91 
Sorry, have you made any progress on this task since then...? :eyes: 
If it seems difficult, I am already in a position to submit a PR on my end, so I am thinking of submitting a PR...? :bow:

**Comment by chankiri91** [comment]
@Corvus400 
I haven't made significant progress on the task as of now. I would appreciate it if you could submit PR.🙇‍♂️

**Comment by Corvus400** [comment]
@chankiri91 
Understood!🫡

@takahirom 
Could you please change the assignment to yourself?

**Comment by takahirom** [comment]
@Corvus400 We've received a lot of help! Thank you!
