### ISSUE TITLE
Proper layout of AssistChip in the archive portion of the timetable detail screen.

### ISSUE THREAD

**Issue by swimmy-reo** [DroidKaigi/conference-app-2023#335]
## Summary 
Proper layout of AssistChip in the archive portion of the timetable detail screen.

## Why
In the archive section of the timetable detail screen, there is a difference in the placement of the AssistChip from Figma.
Also, the wording is incorrect and has been corrected.

| current situation | ideal situation |
| ---- | ---- |
| <img width="300" alt="image" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/ffd2719b-8ca6-4210-b66e-9bb52526a362"> | <img width="300" alt="image" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/e1820314-c65c-4004-bc84-ee29214196fe">|

## Goal
- [ ] The two are equally sized and evenly distributed, just as in the ideal situation of the squash.
- [ ] Change "ドキュメント" to "資料

## Reference
feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableItemDetailContent.kt

[Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&mode=design&t=nYkOrUCLfaA83DTm-0)

**Comment by toastmeister1** [comment]
🙋‍♂️
