### ISSUE TITLE
Add icon to message in TimeTableListItem

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#336]
- Add error icon to TimeTableListItem
- Figma: https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54477-38724&mode=dev
<img width="300" alt="スクリーンショット 2023-08-03 23 05 52" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/db3e2154-8f3c-4033-82db-a576dd01ad7a">

As it | To be
:--: | :--: 
<img width="219" alt="スクリーンショット 2023-08-03 23 12 38" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/e5555481-19c7-45c7-a2df-16efd3cfdd71"> | <img width="207" alt="スクリーンショット 2023-08-03 23 12 26" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/87fa18c2-6f6c-40e0-9ab6-bd61e1fc5fab">

**Comment by yuheikawakami** [comment]
🙋‍♂️

**Comment by swimmy-reo** [comment]
thanks,  please!!  👍
