### ISSUE TITLE
Add TimetableItemDetailContent Compose Preview

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#339]
https://github.com/DroidKaigi/conference-app-2023/blob/0e3b440a58c565f7ffe71e42d5330574367c5d1a/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableItemDetailContent.kt#L47

https://developer.android.com/jetpack/compose/tooling/previews

**Comment by winstonmoon** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned

**Comment by takahirom** [comment]
@winstonmoon Thanks for your inquiry, Could you elaborate what happened to your preview? It says error message or something?

**Comment by winstonmoon** [comment]
@takahirom 
sorry these is no error message but when locale with ja_JP and en_US, preview shows only Japanese.
<img width="1218" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/60098120/f676ff19-9c31-4b6e-a563-ecae9f5b63b6">

when I change locale to ja and en, preview shows both language.
<img width="1214" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/60098120/46f08e03-a452-429a-926c-ef61e24788d7">
