### ISSUE TITLE
Change bookmark icons in TimetableTopArea

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#356]
Please change Icon to bookmark instead of bookmarks to clarify not bookmarking

Before | After
:--: | :--:
<img src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/0e65f1da-0fe3-4653-98e0-a889267b8cfb" width="300" /> | <img src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/27b1e4d7-e04f-4825-ba26-b9b43067da6a" width="300" />

**Comment by sanao1006** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
