### ISSUE TITLE
Each row of Contributor Screen should navigate to Github page when clicked

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#376]
**Idea Description**
Each row should navigate to github page which sent by API

**Reference images and links**
<img width="167" alt="258795706-e7d57806-df65-4f76-aeb3-304aaac71ce4" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/43b0ba6d-0e70-48c9-be64-0a275767294a">

**Comment by tarumzu** [comment]
I'd like to try this issue!
