### ISSUE TITLE
Share button should enabled

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#377]
**Idea Description**
Currently share button is not working.
Please enable share function.

**Reference images and links**
<img width="201" alt="258797112-9d2f6fca-333b-4cf8-bc35-f50dd0ae5a06" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/43767445/0df65a03-9423-404a-8f67-ca6e0d315f6d">

**Comment by matsuurayuki1219** [comment]
@takahirom 
This issue is now blocked, but when it opens, I will try it 🙏
Is it possible ??

**Comment by takahirom** [comment]
@matsuurayuki1219 It is ok! I assigned you!

**Comment by matsuurayuki1219** [comment]
@takahirom 
Thank you !!
When you remove the `blocked label` from this issue  please tell me, and I will fix it 👍

**Comment by takahirom** [comment]
@matsuurayuki1219 The web page is out. We can move on this issue!

**Comment by Corvus400** [comment]
@matsuurayuki1219 @takahirom
If it seems difficult to complete the task, I would like to receive this task myself.🙋

**Comment by takahirom** [comment]
If @matsuurayuki1219 doesn't respond by noon, please go ahead 🙏

**Comment by matsuurayuki1219** [comment]
@Corvus400 
You may take this issue instead of me.

**Comment by Corvus400** [comment]
@matsuurayuki1219 @takahirom 
Understood!
I'll do it instead!💪

**Comment by takahirom** [comment]
Thanks!
