### ISSUE TITLE
Add room and time headers on timetable screen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#378]
## What is required
There is no room and time headers on timetable screen now. So let's add them!

![258837222-2ec1b7ec-c2ea-46da-a962-9f9a13b7db33](https://github.com/DroidKaigi/conference-app-2023-images/assets/67794229/059f028a-6342-4df2-a492-7e98824887f4)

## Reference
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54575-40128&mode=design&t=QI1jRObq4KgYchCJ-0

**Comment by takahirom** [comment]
Thanks! Assigned 👍
