### ISSUE TITLE
Toggle icons when switching timetable style

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#379]
## What is required
Need to toggle the icon when the timetable is grid style.

![258838796-38b4d516-6400-44e2-8203-f77b7e95d40d](https://github.com/DroidKaigi/conference-app-2023-images/assets/67794229/3ebf15c6-7fe2-4f1b-b9ff-5c37c456eea8)

## Reference
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54575-40128&mode=design&t=QI1jRObq4KgYchCJ-0

**Comment by tkhs0604** [comment]
@suzumi726 
Sorry, let me unassign you once since this issue's status has not changed for a while 🙇‍♂️

**Comment by naotama2002** [comment]
🙋 Can I try this one?
