### ISSUE TITLE
Apply the proper calendar icon on timetable item detail screen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#380]
## What is required
A different calendar icon is set on timetable item detail screen now, so let's replace it with the one which has plus `+` mark.

![258841534-8ccce4d1-de9f-408f-bd86-e1e3eb88ce43](https://github.com/DroidKaigi/conference-app-2023-images/assets/67794229/8481e8db-fa23-470b-a581-646a8144e001)

## Reference
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54902-39762&mode=design&t=FstLHmTOBbCbVZhz-0

**Comment by lhoyong** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned
