### ISSUE TITLE
Fix a bottom navigation's label from Stamps to Badges

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#381]
## What is required
Let's update a label in the bottom navigation.

![258844407-54c46717-ed82-4533-965b-646df4e056fd](https://github.com/DroidKaigi/conference-app-2023-images/assets/67794229/f5ac86d5-96ef-4187-9946-ad1796a461e6)

## Reference
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=50721-10370&mode=design&t=fN1JCIoLdAjxr5L6-0

**Comment by KwakEuiJin** [comment]
i want to solve this issue too

**Comment by kudpig** [comment]
🙋‍♂️
