### ISSUE TITLE
Replace the no result icon on timetable search screen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#382]
##What is required
Currently 🔍 icon is displayed if there is no search result, so let's replace it with the proper one.

![258845633-1e6d225a-6e9c-4476-a256-941d422768cf](https://github.com/DroidKaigi/conference-app-2023-images/assets/67794229/e7ffefc5-dee3-4b30-b87c-a56a889e8074)

## Reference
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55032-63555&mode=design&t=FstLHmTOBbCbVZhz-0

**Comment by KwakEuiJin** [comment]
Can I take the issue?

**Comment by tkhs0604** [comment]
Sure! Assigned you 👍
