### ISSUE TITLE
Make the time label stickable on timetable screen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#383]
## What is required
It is better for the time label on timetable screen to be stickable when scrolling.
<img src="https://github.com/DroidKaigi/conference-app-2023-images/assets/67794229/19bf1779-6743-4875-914d-b4f25c735332" width="300">

## Reference
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54902-43788&mode=design&t=byz4fuqUd6q4I08I-0

**Comment by KwakEuiJin** [comment]
I want to resolve this issue, can i take the issue?

**Comment by takahirom** [comment]
Thanks! Assigned!

**Comment by KwakEuiJin** [comment]
I'm working on this issue. It is a rather difficult problem, so it will take some time 🥲 but i keep trying

**Comment by KwakEuiJin** [comment]
https://github.com/DroidKaigi/conference-app-2023/assets/93872496/3906325b-b108-4484-bd88-f605e44b2c55

@takahirom 
@tkhs0604 

Please check if this is a good way

However, in the case of the last index, the time is not visible. We'll keep looking for a solution

**Comment by tkhs0604** [comment]
@KwakEuiJin 
I completely missed your comment. I really apologize 🙇‍♂️

Thank you so much for your investigation and trial implementation.
The following comments are just my impression:
- Looks much better than the current implementation
- The behavior does not look a general sticky header, but it's acceptable for me.
- I would like the last duration information to be displayed (I think it is one of this issue's requirements 😢)

FYI: This may be similar to what we want.
https://fvilarino.medium.com/creating-a-sticky-letter-list-in-jetpack-compose-2e7e9c8f9b91

@takahirom 
Do you have any comments about the above movie? 👀

**Comment by S-H-Y-A** [comment]
I didn't realize this issue and @KwakEuiJin has been trying to implement that.
I already made it. ( Look → #775 )
If you have any advice to me, give me some one!

**Comment by KwakEuiJin** [comment]
@S-H-Y-A 
I applaud the implementation in a better way. I will look at your code and study more 👍

@tkhs0604 
Please change assigned, thanks

**Comment by S-H-Y-A** [comment]
#775 was marged.
I close this issue.

**Comment by takahirom** [comment]
Thanks!
