### ISSUE TITLE
Implement filtering feature except "event date"

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#384]
## What is required
The filtering feature is being implemented but only for "event date" now. So let's implement for the other conditions.
![258847872-63d0efb4-f19e-447d-81d5-167230a5c1a0](https://github.com/DroidKaigi/conference-app-2023-images/assets/1386930/0cc5acda-5176-4e19-a1b1-852d57f1b0f8)

## Reference
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54918-45437&mode=design&t=FstLHmTOBbCbVZhz-0

**Comment by kitakkun** [comment]
I would like to try this issue ✋🏻

**Comment by kitakkun** [comment]
I’m sorry to bother you.

I’m currently working on this issue, but bumped into these two questions.
- Localization
- Language options

### Localization
At this moment, both "event date" and "category" are fully localized, but others are not. I’m wondering how should I localize session-type and supported-language options.

As far as I know, there are four session types, AFTER_PARTY, LUNCH, NORMAL, and WELCOME_TALK.
<img width="443" alt="Screenshot 2023-08-15 at 23 06 39" src="https://github.com/DroidKaigi/conference-app-2023/assets/48154936/b7454ec1-627d-4ece-9aeb-8145637a7b4b">

Do you have any plan to make these raw response values to be localized on the server side (like categories)?
Or, should I localize them manually on the client side?

### Language Options
There are two options of languages, Japanese and English. But precisely, there are four options. Japanese, English, Japanese(Interpretation), and English(Interpretation). 
Should I treat interpreted one and native one differently, or treat them as a single same option?

<img width="439" alt="Screenshot 2023-08-15 at 23 07 47" src="https://github.com/DroidKaigi/conference-app-2023/assets/48154936/737f5398-66f5-432d-a08b-6a2e5af7b1cc">


Thank you in advance.

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I don't have a strong opinion on this. I think having something is better than having nothing.
It's up to you, as we can fix it after you make the change!

**Comment by kitakkun** [comment]
Thank you for your quick reply.
I will try to implement it in my own way and then open a Pull Request to make it better :)
I'm sorry for asking without actual source code 🙏🏻
