### ISSUE TITLE
[iOS] Show room info of each session on timetable screen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#387]
## What to do
No room info of each session is displayed, so let's add it.
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/81587370-9870-4fca-a235-c2c288222d3a" width="300">

## Design
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54477-38724&mode=design&t=kf8tT9D4davWhDvh-0

**Comment by matsuurayuki1219** [comment]
Can I take this issue ?? I want to try it 😊

**Comment by matsuurayuki1219** [comment]
Can I take this issue ??

**Comment by tkhs0604** [comment]
@matsuurayuki1219 
Thank you for raising your hand! Assigned!

**Comment by matsuurayuki1219** [comment]
@tkhs0604 
I have trouble setting up the environment for building iOS application.
(I'm a beginner of KMM application, so if you get a chance, please teach me 🙏)

## Problem
When creating iOS simulator, the waring message have been shown like the below.

<img width="800" src="https://github.com/DroidKaigi/conference-app-2023/assets/105269911/e8b4a019-37c6-4fd2-ad6c-5fbae2664173"/>

## Environment
I wrote my development environment information below.
- Android Studio: Giraffe 2022.3.1
- Xcode: 14.3.1

Also, when opening Xcode, the waring message have been shown like the below.

<img width="800" src="https://github.com/DroidKaigi/conference-app-2023/assets/105269911/757bb716-1011-4c93-b6dc-ace3e675fe9a"/>

## MEMO
- I installed kdoctor and checked whether my environment is valid for KMM project.
- I created a new project for KMM, and building ios application was successful.

**Comment by tkhs0604** [comment]
@matsuurayuki1219 
Sorry for my late reply, and I really appreciate your challenge for KMM project 🙌

I read your information about your development environment.
The message on Xcode means that we need to update the version of Xcode since Swift 5.9 is available only after Xcode 15.
https://developer.apple.com/support/xcode/
So, could you update your Xcode version to **15.0 Beta 6** at first?

Regarding the version of Xcode, the README is outdated a bit, so we will update it as soon as possible 🙏
The other information is up to date. Please read this section too 🙇‍♂️
https://github.com/DroidKaigi/conference-app-2023#ios

**Comment by matsuurayuki1219** [comment]
@tkhs0604 
Thank you for your detail explanation 🙇

>could you update your Xcode version to 15.0 Beta 6 at first?

I see your point. However, I can't upgrade the version of Xcode because of our work in my company ...

So is it ok to leave this issue ?? 🙇

**Comment by tkhs0604** [comment]
@matsuurayuki1219 
Oh, I see 😢 Anyway, thank you for your challenge to KMM project 🙇‍♂️
We are looking forward to your another challenge! 💪
