### ISSUE TITLE
[iOS] Implement grid-style timetable

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#390]
## What to do
We have implemented only list-style timetable for now.
So, please implement grid-style one and add a function to switch them.

## Design
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54575-40128&mode=design&t=kf8tT9D4davWhDvh-0

**Comment by tkhs0604** [comment]
Oh, no one has challenged this screen yet, so let me give it a try! 🙆‍♂️

**Comment by ry-itto** [comment]
@tkhs0604 
Thank you! Assigned 👍🏼

**Comment by tkhs0604** [comment]
@ry-itto 
Unfortunatelly, I can't afford to challenge 1 big issue these days, and I think this page is essential and thus has high priority to implement.
So let me unassign myself once 😭
