### ISSUE TITLE
[iOS] Toggle the bookmark icon on timetable screen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#391]
## What to do
If the session is bookmarked, the icon should be filled one.
Please add a feature to toggle them.

## Design
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54477-38724&mode=design&t=kf8tT9D4davWhDvh-0

**Comment by coffmark** [comment]
🙋‍♂️

**Comment by ry-itto** [comment]
@coffmark 
Thanks! Assigned 👍🏼

**Comment by coffmark** [comment]
I would like to confirm, The goal of this task is to be able to toggle bookmark icons ON/OFF (without network communication)?

**Comment by ry-itto** [comment]
@coffmark 
Oh, ,sorry this overview isn't correct 🙇🏼 

Current bookmark icon on timetable header isn't correct, so please apply correct one 🙏🏼 
<img width="407" alt="スクリーンショット 2023-08-16 10 59 11" src="https://github.com/DroidKaigi/conference-app-2023/assets/30540303/8401b1af-5684-434b-8085-a86d79aee6ee">

**Comment by tkhs0604** [comment]
It's my fault 🙇‍♂️

**Comment by coffmark** [comment]
I got it! 🙆‍♂️
