### ISSUE TITLE
[iOS] Apply app icons

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#392]
## What to do
No app icon is set for iOS app for now.
Please download the icons from the following Figma link and apply them.

## Design
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55674-97357&mode=design&t=kf8tT9D4davWhDvh-0

**Comment by coffmark** [comment]
🙋‍♂️

**Comment by upon0426** [comment]
Thanks! Assigned you!
