### ISSUE TITLE
[iOS] Introduce Observable framework

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#394]
## What to do
Now we can use the brand-new state management system, Observable framework.
Let's migrate to the framework.

Official migration guideline: https://developer.apple.com/documentation/swiftui/migrating-from-the-observable-object-protocol-to-the-observable-macro

## Design
N/A

**Comment by l2hyunwoo** [comment]
I think I can resolve this issue!

**Comment by tkhs0604** [comment]
Awesome! Let me assign you!

**Comment by l2hyunwoo** [comment]
After more investigation for [Observable Macro](https://developer.apple.com/documentation/swiftui/migrating-from-the-observable-object-protocol-to-the-observable-macro), it should be needed iOS version upper than 16. So it would be hard to apply, and I think we should reconsider about this issue.

**Comment by tkhs0604** [comment]
@l2hyunwoo 
I really appreciate your investigation! 
I discussed that with other maintainers, and concluded we didn't apopt this framework for now.
So, let me close this issue 🙇‍♂️

Again, thank you for your contribution!
