### ISSUE TITLE
[iOS] Setup type safe access to L10n 

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#397]
## What to do
- No localization settings for this iOS app now. Please setup localization settings and setup module that can access localization strings with type safe way. (e.g. `L10n.Timetable.title` )
  - Maybe Xcode 15 way is useful. If this way isn't good, `SwiftGen` might be better.

<img src="" width="300">
## Design

**Comment by coffmark** [comment]
🙋‍♂️

**Comment by RyuNen344** [comment]
Thank you, assigned!

**Comment by coffmark** [comment]
I have started implementation but I'm not doing well 🙏  (I'm thinking of using SwiftGen)
It will take a little more time, sorry 🙏

**Comment by coffmark** [comment]
@ry-itto 
Sorry, I've been working on this issue for the last few days but n't know what the solution...

I chose XcodeGen to access strings with type safe but could not achieve multilingual support.

I'm so sorry, could you please remove the assignment?

**Comment by woxtu** [comment]
🤚

**Comment by ry-itto** [comment]
@woxtu 
Thanks! Assigned👍
