### ISSUE TITLE
[iOS] Apply latest design for FloorMap

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#398]
## What to do

- Current iOS FloorMap UI isn't latest. Please apply latest design for FloorMap.

## Design

https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55876-19767

**Comment by coffmark** [comment]
I'll try!

**Comment by momomomo111** [comment]
@coffmark  Nice! Assigned!

**Comment by coffmark** [comment]
Let me ask you a question about the scope of implementation!

Latest FloorMapView diff is
- Map Image (1F and B1F) [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-69948&mode=dev)
- Event information list [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-70007&mode=dev)
- Footer segmented control [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-70041&mode=dev)

Please let me know the scope of this ticket! 🙏
Is it correct that all task perform?

**Comment by ry-itto** [comment]
@coffmark 
Yes! it is correct 🙏🏼 
All diffs in FloorMapView are in scope of this issue!

**Comment by coffmark** [comment]
OK! @ry-itto 

The task is big, so I would like to split task and submit PR! (total 3 PR)

1. Change map image(1F and B1F)
2. Add footer segmented control (and can change 1F and B1F view)
3. Add Event information list

---

I would like to ask an additional question, Is it correct that the event information list displays dummy data?

**Comment by ry-itto** [comment]
@coffmark 

> Is it correct that the event information list displays dummy data?

Yes! That make sense!

**Comment by coffmark** [comment]
@ry-itto 
Sorry for the delay, I will submit PR by tomorrow 🙏
