### ISSUE TITLE
[iOS] Setup DI for some shared instances

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#399]
## What to do

- Current iOS App refers some shared instances directly. Please refer those instances with DI way.
- Target
  - ViewProviders
  - KMM module instances (ApiClient,,,)

**Comment by HironobuIga** [comment]
I'd like to contribute :)
I'll intend to use SwiftLee's way.
Ref: https://www.avanderlee.com/swift/dependency-injection/
