### ISSUE TITLE
[iOS] Open appropriate url from AboutView

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#400]
## What to do

- No actions for some tiles that should open url with Safari in AboutView. Please implement those with creating new module.
- This [PR](https://github.com/DroidKaigi/conference-app-2022/pull/451) may be useful.

**Comment by HironobuIga** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned
