### ISSUE TITLE
[iOS] Implement LicenseView

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#402]
## What to do

- Currently, iOS App don't have Licence page. Please implement LicenseView with using https://github.com/cybozu/LicenseList .

**Comment by ry-itto** [comment]
@HironobuIga 
Sorry, I missed this too.. 🙇🏼 
Assigned 👍🏼

**Comment by HironobuIga** [comment]
@ry-itto 
No problem! Thank you :)
