### ISSUE TITLE
Display Map, Floor Information, and Page Title on FloorMapScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#420]
**Idea Description**
Integrate the temporary map available on [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI) into the FloorMapScreen. The task includes:
   - Importing and displaying the map as it is.
   - Displaying the information related to the floor.
   - Adding the appropriate page title.
Simply replicating the design and displaying these elements is sufficient.

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023-images/assets/51113946/9f3819c2-f86d-4e53-933a-01483e72ee8b)

**Comment by mikanIchinose** [comment]
🙋 I'd like to try this issue!

**Comment by takahirom** [comment]
Thank you for taking this! Assigned 👍
