### ISSUE TITLE
Display SideEvent List on FloorMapScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#421]
**Idea Description**
Add SideEvent items to the FloorMapScreen to complete the list. Place the list's Composable functions in the `section` package, and create the UiState accordingly. More details can be found [here](https://github.com/DroidKaigi/conference-app-2023#section).

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023-images/assets/51113946/5e1304d8-c131-41fa-ad8b-fdb2cb168075)
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55876-19767&mode=dev

**Comment by morayl** [comment]
I would like to try on this issue!

**Comment by takahirom** [comment]
Thanks! Assigned 👍
