### ISSUE TITLE
Implement Floor Switch and Highlighting Gradient on FloorMapScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#422]
**Idea Description**
Add a switch to change the floor number on the FloorMapScreen, along with a gradient to make it stand out, as per the design on [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI). The task includes:
   - Implementing a switch that allows users to change the floor number.
   - Adding a gradient to highlight the floor switch.
  
The main goal is to replicate the design and functionality as shown in the provided design.

**Reference images and links**
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55876-19767&mode=dev

![image](https://github.com/DroidKaigi/conference-app-2023-images/assets/51113946/6f029c3c-a3c4-4550-952e-5e8008a3594d)

**Comment by Masaki-U** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned
