### ISSUE TITLE
Implement Sponsor List and Design on SponsorsScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#424]
**Idea Description**
Create and display the sponsor list on the SponsorsScreen, and apply the corresponding design as shown on [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI). The task includes:
   - Implementing the sponsor list.
   - Placing the list's Composable functions in the `section` package. More information is available [here](https://github.com/DroidKaigi/conference-app-2023#section).
   - Creating the UiState as needed.
   - Applying the design to match the provided Figma layout.

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023-images/assets/51113946/4b12c52c-fd54-472e-9681-88001973363f)

**Comment by l2hyunwoo** [comment]
It looks interesting. I want to take this one too.
