### ISSUE TITLE
Implement Top Section of AboutScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#429]
**Idea Description**
Implement the top section of the AboutScreen, as divided into three parts in the design on [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI). The task includes:
   - Implementing the design for the top section only.
   - Adding the design to the existing empty implementation in AboutDroidKaigiDetail.
   - No need to create any navigation behavior; simply replicating the design is sufficient.

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023-images/assets/51113946/dba72127-abd6-451e-a4b5-c8b3e2570084)

**Comment by Corvus400** [comment]
I would like to work on this task🙋

**Comment by takahirom** [comment]
Thanks as always!! Assigned!
