### ISSUE TITLE
Implement Middle Section of AboutScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#430]
**Idea Description**
Implement the middle section of the AboutScreen, as divided into three parts in the design on [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI). The task includes:
   - Implementing the design for the middle section only.
   - Adding the design to the existing empty implementation in aboutCredits and aboutOthers.
   - No need to create any navigation behavior; simply replicating the design is sufficient.

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023-images/assets/51113946/7094416b-f2e2-4125-9f20-9fd5320e5d0f)

**Comment by Corvus400** [comment]
Since I addressed issue #429 in #481, can I work on this task as well?  🙋

**Comment by takahirom** [comment]
Thanks for addressing this high priority issues!
