### ISSUE TITLE
Implement Staff Screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#435]
**Idea Description**
Develop the Staff Screen from scratch, following the available design on [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI). This will be a substantial task as there is no existing implementation. The endpoint for this feature will be `events/droidkaigi2023/staff`. Please allocate enough time and resources to complete this task.

**Reference images and links**
<img width="422" alt="260285191-b390ee9d-e387-4cce-850e-3352473f4239" src="https://github.com/DroidKaigi/conference-app-2023-images/assets/1386930/4b735181-7772-4959-a131-81d176d0cec6">

**Comment by Naoki-Hidaka** [comment]
I would like to work on this issue!

**Comment by upon0426** [comment]
Thanks! Assigned!

**Comment by Naoki-Hidaka** [comment]
@upon0426 

When I look at Figma, I see the notation Team under UserName, but the API response for `events/droidkaigi2023/staff` does not seem to contain any information about the team.

Where should I get this information from?

```
{
    "status":"OK",
    "staff":[
        {
            "id":52602975,
            "username":"akari317017",
            "profileUrl":"https://github.com/akari317017",
            "iconUrl":"https://avatars.githubusercontent.com/u/52602975?v=4",
            "icon32Url":"https://avatars.githubusercontent.com/u/52602975?v=4&size=32",
            "icon64Url":"https://avatars.githubusercontent.com/u/52602975?v=4&size=64",
            "icon128Url":"https://avatars.githubusercontent.com/u/52602975?v=4&size=128"
        },
        {
            "id":3901275,
            "username":"chihokotaro",
            "profileUrl":"https://github.com/chihokotaro",
            "iconUrl":"https://avatars.githubusercontent.com/u/3901275?v=4",
            "icon32Url":"https://avatars.githubusercontent.com/u/3901275?v=4&size=32",
            "icon64Url":"https://avatars.githubusercontent.com/u/3901275?v=4&size=64",
            "icon128Url":"https://avatars.githubusercontent.com/u/3901275?v=4&size=128"
        },
        ....
    ]
}
```

**Comment by jmatsu** [comment]
@Naoki-Hidaka 
Hi, I'm replying to you on behalf of @upon0426.

We are sorry for confusing you. Figma is not up-to-date and we have decided not to show the team information. 

@nobonobopurin
Could you please update the Figma design to remove the team information?

**Comment by Naoki-Hidaka** [comment]
>  Figma is not up-to-date and we have decided not to show the team information.

I see
Then I will implement it without the Team notation.
Thank you very much!

**Comment by upon0426** [comment]
@Naoki-Hidaka 
Thanks for checking the behavior here!

Yes, if user tap each staff member row, it should navigate to github profile page. You may have already noticed, you can get the URL from the API response.

**Comment by Naoki-Hidaka** [comment]
@upon0426 
Thank you very much!

How would you like your github profile page to appear?
I think there is a WebView or default external browser.

**Comment by upon0426** [comment]
@Naoki-Hidaka 
Either is okay. But if possible please open with external browser.

**Comment by takahirom** [comment]
You can refer to this 🙏 
https://github.com/DroidKaigi/conference-app-2023/blob/main/app-android/src/main/java/io/github/droidkaigi/confsched2023/KaigiApp.kt#L153

**Comment by nobonobopurin** [comment]
@jmatsu @Naoki-Hidaka 
I've removed the team information from the[ 'Staff' page](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55032-59358&mode=design&t=zzJUtygJDKQvWcsZ-4) on Figma.
