### ISSUE TITLE
Add CustomTab Implementation for Web Navigation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#439]
**Idea Description**
Implement CustomTab functionality to allow navigation to web links from the app. This will be used to handle links within the About Screen and potentially other areas. Please ensure that the implementation integrates seamlessly with the existing app structure and follows best practices for web navigation within mobile applications.

**Reference images and links**

**Comment by fornewid** [comment]
There is no implementation for WebView in kotlin multiplatform.
Is it correct to mean CustomTab in `androidx.browser`?
https://developer.android.com/jetpack/androidx/releases/browser

If so, I'd like to try. 🙋

**Comment by takahirom** [comment]
I mean so! Thanks!
