### ISSUE TITLE
Add Accessibility Dump Screenshot Test to TimetableScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#444]
**Idea Description**

Implement an accessibility dump screenshot test for the TimetableScreen using Roborazzi. The task involves:
   - Adding the `checkAccessibilityCapture()` method to the `TimetableScreenRobot` class.
   - Implementing the `checkLaunchAccessibilityShot()` in the `TimetableScreenTest` class.

Here's the code snippet for `TimetableScreenRobot`:

```kotlin
fun checkAccessibilityCapture() {
    composeTestRule
        .onRoot()
        .captureRoboImage(
            roborazziOptions = RoborazziOptions(
                captureType = RoborazziOptions.CaptureType.Dump(
                    explanation = Dump.AccessibilityExplanation,
                )
            )
        )
}
```

**Reference images and links**

**Comment by kktaro** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned!
