### ISSUE TITLE
Fix and Enable Zoom and Scrolling in Timetable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#445]
**Idea Description**

The timetable's zoom functionality has caused the scrolling to be disabled, and the feature has been temporarily turned off. The task is to investigate and fix this issue so that both zoom and scroll functionalities can work together seamlessly.

Please refer to the specific code where the zoom has been disabled:
[TimetableGrid.kt](https://github.com/DroidKaigi/conference-app-2023/blob/5f348f5a32f3e877f71db9f57fd8f681955bb263/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableGrid.kt#L173)

Ensure to test the changes thoroughly to confirm that both functionalities are working correctly without conflicting with each other.

Feel free to reach out if you have any questions or need further assistance.

**Reference images and links**

**Comment by syam4869** [comment]
I would like to work on this issue!

**Comment by takahirom** [comment]
Thanks! Assigned!
