### ISSUE TITLE
Align Session Heights in Timetable Grid Display According to Time Duration

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#447]
**Idea Description**
In the timetable's grid display, sessions with the same duration are currently adjusting their heights based on the length of the titles, causing inconsistency in the timetable's appearance. The task is to fix this issue by implementing the following:
   - Set a fixed height for all sessions, regardless of the title length.
   - Resize the title text to fit within the fixed height if it is too long, ensuring that it does not wrap and extend the session box.

The goal is to maintain a uniform appearance for the timetable grid, with all sessions of the same duration having the same height, regardless of the content.

Please make sure to test the changes across different screen sizes and content scenarios to ensure consistent behavior.

Feel free to reach out if you have any questions or need further clarification.

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023-images/assets/51113946/b73527df-e890-4e9c-a232-99658080dd2c)

**Comment by shxun6934** [comment]
I try this issue!! 🙋‍♂️

**Comment by takahirom** [comment]
Thanks for taking this issue! Assigned 👍

**Comment by shxun6934** [comment]
@takahirom 
May I ask you some questions?

1. Currently, the session height is a numerical value that considers the session time, but is there any problem with a fixed value? If it is a fixed value, is it okay to set the fixed height to 153dp?
2. Is 14sp okay if the title fits in the box, and 12sp if it doesn't?

## 1. Currently, the session height is a numerical value that considers the session time, but is there any problem with a fixed value? If it is a fixed value, is it okay to set the fixed height to 153dp?

In [the corresponding code](https://github.com/DroidKaigi/conference-app-2023/blob/main/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableGrid.kt#L282-L283), the height of the session grid item is changed depending on the session time.

Is it okay to set the same fixed value even if the session time is different?

Also, if I want to use a fixed value, I would like to use 153dp set in Figma.

<img width="182" alt="スクリーンショット 2023-08-15 17 12 08" src="https://github.com/DroidKaigi/conference-app-2023/assets/23094546/f4d0c2a5-69ff-422c-a880-b479756d0c8e">


## 2. Is 14sp okay if the title fits in the box, and 12sp if it doesn't?

In the session grid item style in [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-48998&mode=design&t=8jU48xcDurlJy16N-0), the title typography settings were set to 14sp and 12sp, so I'm going to use these values.

<img width="532" alt="スクリーンショット 2023-08-15 19 20 26" src="https://github.com/DroidKaigi/conference-app-2023/assets/23094546/a256cb05-455b-4166-89d2-2a3df9568a2c">
<img width="511" alt="スクリーンショット 2023-08-15 19 20 41" src="https://github.com/DroidKaigi/conference-app-2023/assets/23094546/6f9b5cbb-3566-4d59-b1bd-b70899494f1e">

**Comment by takahirom** [comment]
I think you may refer to last year's item implementation. But it's up to you! 🙏
