### ISSUE TITLE
[iOS] Use cached image

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#456]
**Idea Description**

- Currently, iOS app uses `AsyncImage` that isn't cached downloaded image. Please apply cache for images 🙏🏼 

**Reference images and links**

**Comment by ry-itto** [comment]
@HironobuIga 
I missed..! Thanks! Assigned :bow:

**Comment by HironobuIga** [comment]
@ry-itto 
No problem! Thank you :)

**Comment by HironobuIga** [comment]
@ry-itto 
Could I ask one question?
I encountered this warnings and error when I try to build xcodeproj.

> Could not find or use auto-linked framework 'FirebaseAuth': framework 'FirebaseAuth' not found
> Could not find or use auto-linked framework 'FirebaseCore': framework 'FirebaseCore' not found
> Could not find or use auto-linked framework 'FirebaseRemoteConfig': framework 'FirebaseRemoteConfig' not found
> Undefined symbols:

Do you know how to resolve this issue...?
I use M2 chip mac and perhaps it makes problem...?

**Comment by HironobuIga** [comment]
I succeed building iOS app. So the problem is resolved now.
