### ISSUE TITLE
Talkback not working with DroidKaigi icon at Timetable screen

### ISSUE THREAD

**Issue by fumiya-kume** [DroidKaigi/conference-app-2023#461]
**Describe the bug**
Talkback not working with DroidKaigi icon at Timetable screen. Talkback should explain the content.

The contentDescription should have.

**To Reproduce**
1. Go to TimeTable screen
2. Tap the DroidKaigi icon (top left)

**Expected behavior**
Playback the explanation of DroidKaigi icon or content description.

**Screenshots**

The attendees can't select by the talkback, so selecting the conference title text instead.

<img src="https://github.com/DroidKaigi/conference-app-2023/assets/16269075/81c3200a-d353-40c2-945a-ff4e4e65e106" width="50%" />

**Comment by takahirom** [comment]
Thanks! Accessibility is vital. Do you mean we should use the contentDescription attribute?

**Comment by fumiya-kume** [comment]
yup, working well the talkback with set the `content description`

**Comment by NUmeroAndDev** [comment]
We should ask the project owner's opinion, it's a difficult case.

In my opinion is that icon doesn't need content description.
Because it can function as an app without a readout, and in some cases it can take up time and unnecessary focus.

**Comment by fumiya-kume** [comment]
> We should ask the project owner's opinion, it's a difficult case.
> 
> In my opinion is that icon doesn't need content description. Because it can function as an app without a readout, and in some cases it can take up time and unnecessary focus.

That's make sense, I'm not good the future plan of app honestly. so up to project owners too.

**Comment by takahirom** [comment]
Thanks for your opinion. I agree with you. Let me close this 🙏
