### ISSUE TITLE
Remove "interpretation target" chip and align the chip to the Figma

### ISSUE THREAD

**Issue by fumiya-kume** [DroidKaigi/conference-app-2023#463]
**Describe the bug**

Timetable screen doesn't working well with BigFont/BigDisplay config.

- The bottom of header content hidden by the sheet.
- Chips can be second line if needed.
- 

**To Reproduce**
1. Go to Timetable screen

**Expected behavior**

The hidden UI should be visible, otherwise, can be consider with designer as well.

**Screenshots**

<img src="https://github.com/DroidKaigi/conference-app-2023/assets/16269075/2b125341-3b40-4060-8a01-47dce1819e0a" width="50%" />

**Comment by takahirom** [comment]
I mean we can remove "interpretation target" chip!

**Comment by tfandkusu** [comment]
🙋
