### ISSUE TITLE
Hide session title at session detail screen when enable the BigFont/BigDisplay

### ISSUE THREAD

**Issue by fumiya-kume** [DroidKaigi/conference-app-2023#464]
**Describe the bug**

The session title hide the top of text when enable the BigFont/BigDisplay

For some of screen are affected, then investigate the cause first?

**To Reproduce**
1. Go to Session detail screen

**Expected behavior**

Showing the session title correctly.

**Screenshots**

<img src="https://github.com/DroidKaigi/conference-app-2023/assets/16269075/c39dcefe-210e-4bb0-b8dd-9d04346d8941" width="50%" />

**Comment by kosenda** [comment]
I would like to challenge this issue 🙋

**Comment by takahirom** [comment]
I'm not sure how you fix it! 😮 But thanks! Assigned 👍

**Comment by kosenda** [comment]
Let me ask you a question!

The `styles` that you are passing to the [ResizeableText](https://github.com/DroidKaigi/conference-app-2023/blob/db399d1e03797397cb0818dd38afcf6cd6a21275/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableItemDetailScreenTopAppBar.kt#L78C22-L78C22) param in [TimetableItemDetailScreenTopAppBar](https://github.com/DroidKaigi/conference-app-2023/blob/db399d1e03797397cb0818dd38afcf6cd6a21275/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableItemDetailScreenTopAppBar.kt#L26), `MaterialTheme.typography.titleSmall` is the smallest, so I can't make the text any smaller.
I would like to ask you, which of the following three ways do you think is the best way to eliminate the broken characters?
- Allow the `styles` param to be set to something smaller
- Make two lines into one line when a character is cut off.
- Other than the above two

**Comment by takahirom** [comment]
Sorry let me answer this tomorrow🙇

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Maybe I don't think shifting the text style is a good approach because it is not seamless. So, can we change the size more finely?

It will be this 👀 

> Allow the styles param to be set to something smaller

**Comment by kosenda** [comment]
I would like to make it seamless and fine sized.
I think this will be a very difficult change, so if it seems too difficult, I would like to say "give up" as soon as possible.

**Comment by kosenda** [comment]
Sorry! I give up!

**Comment by takahirom** [comment]
Thank you for your challenge! I'm looking forward your next PR! Unassigined!
