### ISSUE TITLE
Disable backing again during transition from bookmark screen.

### ISSUE THREAD

**Issue by tuxsnct** [DroidKaigi/conference-app-2023#468]
**Describe the bug**
When the back button is repeatedly pressed on the bookmark screen, nothing appears on the screen.

**To Reproduce**
1. Click on 'bookmark'
2. Click on 'back' repeatedly until the transition is complete
3. See blank screen

**Expected behavior**
Make it impossible to press the back button during a transition (when the back button has already been pressed once)
Or some similar way to make it impossible to go back.

**Screenshots**
I've attached a video because it's easier to understand the situation.

https://github.com/DroidKaigi/conference-app-2023/assets/59034394/d688f38f-bd9c-4f62-b47a-a12146a167ef

**Comment by kosenda** [comment]
I would like to challenge this issue 🙋

**Comment by swimmy-reo** [comment]
ok, please!! 👍
