### ISSUE TITLE
[Suggestion] Add support for the predictive back gesture

### ISSUE THREAD

**Issue by chigichan24** [DroidKaigi/conference-app-2023#474]
**Idea Description**
The predictive back gesture is introduced in API level 33. Users will be able to preview whether or not they will back to the home screen when they do a back gesture and will be able to decide whether to stay in the current view or continue. Some applications (e.g., Settings, Spotify) are already introduced.
Under this project, there's no implementation requiring special consideration for `onBackPresed` logic handling. Thus, we can introduce the "predictive back" feature only for updating `AndroidManifest.xml`.

**Reference images and links**
- https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture
- prototype implementation 
  - https://github.com/chigichan24/conference-app-2023/tree/enable-predictive-back
  - https://github.com/DroidKaigi/conference-app-2023/assets/7840108/1ccc287d-0d9c-460f-8799-e6f11b85f978

**Comment by takahirom** [comment]
Looks great! Do you have any concerns?

**Comment by chigichan24** [comment]
AFAIK, there're no side effects or big concerns about this change👍 I'll update the PR status as ready for review.
