### ISSUE TITLE
DroidKaigi's code style is missing features that the IDE supports.

### ISSUE THREAD

**Issue by Pluu** [DroidKaigi/conference-app-2023#477]
Spotless/ktlin recommends using **trailing commas**, 
so setting this style as the default style for your project seems like the right choice.

Is there a reason you didn't add it?

**Comment by takahirom** [comment]
I would like to add it definitely!

**Comment by Pluu** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
