### ISSUE TITLE
[Proposal] Convert object declaration to data object in sealed hierarchies

### ISSUE THREAD

**Issue by l2hyunwoo** [DroidKaigi/conference-app-2023#480]
**Idea Description**

Using data objects with sealed hierarchies

**Reference images and links**

- [Kotlin Official Doc](https://kotlinlang.org/docs/object-declarations.html#using-data-objects-with-sealed-hierarchies)

**Comment by takahirom** [comment]
IDE says we can replace it! 😄

**Comment by l2hyunwoo** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
