### ISSUE TITLE
[iOS] Failed to build iOS

### ISSUE THREAD

**Issue by NakaokaRei** [DroidKaigi/conference-app-2023#484]
**Describe the bug**
I guess iOS build is failed due to following commit.

https://github.com/DroidKaigi/conference-app-2023/commit/f230f348ac9ff576f6c153a447e99d25a3e89dfa#diff-eb794d2bfea8cd56305b12dd123003541116857740cb4db2d798ca5ae76ef3aaL11

**To Reproduce**
1. Follow the instructions in the README
2. Run build DroidKaigi2023 target

**Expected behavior**
The build will be successful.

**Screenshots**
![image](https://github.com/DroidKaigi/conference-app-2023/assets/39183069/787d0c8a-7e88-448a-8fa0-80f02df31879)

**Comment by tkhs0604** [comment]
Thank you for finding the compile error and reporting 🙏
Unfortunately, it sometimes happens since the Android Studio cannot propagate the rename of common module's codes to iOS side 😢

**Comment by takahirom** [comment]
Can you replace it with `Timetable.Companion.fake()`?

**Comment by NakaokaRei** [comment]
> Can you replace it with Timetable.Companion.fake()?

@takahirom 
Yes! I was successful. Thanks!
I will submit PR/

**Comment by takahirom** [comment]
Thanks 🙏
