### ISSUE TITLE
BookmarkFilters Chip has the wrong color applied to it.

### ISSUE THREAD

**Issue by Pluu** [DroidKaigi/conference-app-2023#491]
In my previous work with https://github.com/DroidKaigi/conference-app-2023/pull/469, different colors were mapped to the BookmarkFilters Chip.

We need to check for the existence of Figma later to color it correctly.

According to the M3 guide, a Chip is a secondary container.

- https://m3.material.io/styles/color/the-color-system/color-roles

🙇🙇🙇

**Comment by Pluu** [comment]
🙋

**Comment by takahirom** [comment]
Thanks!
