### ISSUE TITLE
Fix NestedScroll Issue in Timetable Grid to Allow Tab Shrinking on Scroll

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#498]
In the Timetable grid section of the DroidKaigi app, the NestedScroll functionality is not working as expected. As a result, tabs and other elements do not shrink in response to scrolling. This affects the user experience and needs to be addressed.

### Expected Behavior
Tabs should shrink when the user scrolls through the timetable grid.

### Current Behavior
Tabs remain fixed and do not respond to scrolling.

**Comment by usuiat** [comment]
🙋 I want to try this.

**Comment by takahirom** [comment]
Thanks for challenging this!

**Comment by usuiat** [comment]
@takahirom 
So far I have achieved nested scrolling when dragging a TimetableGrid. (Please see the draft PR #659)
However, I have not achieved nested fling behavior. It will take more time to realize it.
Can I submit a PR for only nested scrolling on drag and then create another issue for the remaining fling behavior?

**Comment by NUmeroAndDev** [comment]
>Can I submit a PR for only nested scrolling on drag and then create another issue for the remaining fling behavior?

OK 🙆‍♂️ 
Thank you for working to resolve the issue!
@usuiat

**Comment by usuiat** [comment]
I marked the pull request #659 as ready for review.
