### ISSUE TITLE
Implement Shimmer Effect as Placeholder Instead of "empty" String for Timetable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#500]
**Idea Description**
Currently, the DroidKaigi app displays the string "empty" as a placeholder in certain situations. To enhance the visual appeal, we should replace this with a shimmer effect.

Show a shimmer effect as a placeholder when content is loading or unavailable.

**Reference images and links**

**Comment by sanao1006** [comment]
I would like to work on this issue✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍 
Maybe we can create TimetableSimmerList() or something 👀

**Comment by takahirom** [comment]
@sanao1006 I think this may be a little high-priority issue. Since this is the first experience when you open the app. So let me add a milestone. If you can't meet the milestone let me know 🙇

**Comment by sanao1006** [comment]
@takahirom  I got it!

少々焦ってこのタスクにアサインしてしまったのですが、もし実装で分からない部分があれば質問してもいいのでしょうか？
I was a little hasty in assigning this task, but if there is any part of the implementation that I don't understand, is it okay to ask questions?

**Comment by takahirom** [comment]
もちろんです！もし時間なくてできなそうでも、早めにgive upとか書き込んでいただければ大丈夫です！
Sure! Even if you don't have time, it's ok to write "give up".

**Comment by fornewid** [comment]
FYI :)
Although recently deprecated, there is a **placeholder** library on accompanist.
- https://google.github.io/accompanist/placeholder/
- https://github.com/fornewid/placeholder

**Comment by takahirom** [comment]
I'm not sure which library is the right choice 😅 
* https://github.com/valentinilk/compose-shimmer
* https://github.com/ValeryPonomarenko/compose-shimmer

**Comment by sanao1006** [comment]
@takahirom 
I have a question.
![image](https://github.com/DroidKaigi/conference-app-2023/assets/62137820/39d41d50-2e33-489a-ad69-678321652e06)

Currently, I have implemented a shimmer effect with the configuration shown in the image, but when the `uiState: TimetableSheetUiState` in `TimetableSheet.kt` is Empty, I do not know how many contents to display (the mass in the red box in the image). Currently, I am using the `repeat()` function to display 5 for now. Should I adopt some other method?

現状、画像のような構成でシマーエフェクトを実装したのですが、`TimetableSheet.kt`にある`uiState: TimetableSheetUiState`がEmptyのときは表示させるコンテンツ(画像の赤枠の塊)の個数が分かりません。現状、`repeat()`関数を使ってとりあえず５個表示させています。何か別の方法を採用すべきですか？

https://github.com/DroidKaigi/conference-app-2023/blob/d61800f3a9182478aee126ed6779490d9133baee/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableSheet.kt#L83-L89

I am sorry for the confusing question, I am looking forward to your answer.
質問分かりづらくてすみません、回答お待ちしています

**Comment by takahirom** [comment]
I would use 10 or something because it should be enough size when you use large device. 👀

**Comment by sanao1006** [comment]
OK!  I will create a PR later!
