### ISSUE TITLE
Customize Chip Colors According to Room Labels

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#501]
**Idea Description**

In the DroidKaigi app, we have the opportunity to enhance the visual differentiation of room labels by changing the color of the corresponding Chips.

### Expected Behavior
Chips should have distinct colors based on the room labels they represent.

### Current Behavior
All Chips have the same color, regardless of room label.

### Steps to Reproduce
Provide steps on how to reproduce this issue...

### Additional Information
Provide any additional information or screenshots...

**Reference images and links**
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/f5c8c702-3099-4e32-b1a0-79fcfd7fc403)

**Comment by kosenda** [comment]
I would like to challenge this issue 🙋.

Also, sorry if this is an odd question, but am I correct in understanding that the room color is branched by the `name` (`en`) of the `RoomResponse`, as in the 2022 application?

**Comment by takahirom** [comment]
I think we are having a extention function for room for this year. Can check it?

**Comment by takahirom** [comment]
I would like to use this 🙏  
https://github.com/DroidKaigi/conference-app-2023/blob/192521ac03a3c5c499a5019bfc49be2094a36eeb/core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/model/RoomIndex.kt#L6

**Comment by kosenda** [comment]
Thank you 🙇
