### ISSUE TITLE
Image cache not working: flickering issue when switching screens

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#515]
It appears that the image caching is not working properly in our application. This issue is causing a noticeable flickering effect every time the screen is switched.

### Description
When navigating between different screens, the images seem to reload each time, leading to a brief flicker. This behavior suggests that the images are not being cached as expected.

**Comment by matsuurayuki1219** [comment]
Can I take this issue ??

**Comment by takahirom** [comment]
Thanks! Assigned!

**Comment by matsuurayuki1219** [comment]
@takahirom 
I have one question, I don't know where this problem appears...
Could you please show me where to fix ??

**Comment by takahirom** [comment]
Oh, now it looks fixed. I don't know why but let me close this! Thank you for informing this 🙏
