### ISSUE TITLE
Display Snackbar for Bookmark Confirmation in TimetableItemDetailScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#517]
**Idea Description**
When a user adds a bookmark in the TimetableItemDetailScreen, a Snackbar should appear with the message "Bookmarked successfully."

This enhancement will provide immediate feedback to the user, confirming that the action was successful.

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/87d5ea98-80a6-4090-9bb0-ebf90516d880)

**Comment by KoutaMatsushita** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned!
