### ISSUE TITLE
Add Fake Session to FakeSessionsApiClient for Checking Other Rooms

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#520]
**Idea Description**
We don't have sessions that are associated with other rooms, so we can't verify them in the Screen Shot test. We need to add a fake session to the FakeSessionsApiClient to check the functionality for other rooms.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/blob/1afc72cc9ff53d7dc9c66f2b872848f044120cad/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/data/sessions/FakeSessionsApiClient.kt#L45

**Comment by takahirom** [comment]
You don't have to add test. All you have to do is add sessions using different room

**Comment by Hachimori** [comment]
🙋‍♂️

**Comment by upon0426** [comment]
Thanks! Assigned you!
