### ISSUE TITLE
Search Feature Not Working: Empty Screen Displayed Regardless of Input

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#524]
The current search feature in our application appears to be malfunctioning. Despite entering text into the search field, the result is always an empty screen.

### Description
When users attempt to search by entering text, the expected search results are not displayed. Instead, an empty screen appears every time, making the search feature unusable.

**Reference images and links**

**Comment by chigichan24** [comment]
Can I take this issue?

**Comment by takahirom** [comment]
Thanks for taking this!
