### ISSUE TITLE
Apply stamps initial screen

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#525]
**Description**
We would like you to implement the initial screen for the Stamps screen

**Reference images and links**
<img width="300" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/51113946/2cf64572-7a76-4115-a05a-b64bfe30d0b0">

[Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55416-70904&mode=dev)

**Comment by 5altNaCl** [comment]
やりたいです✋
Stampメニューを押したら、画像のデザインの画面が表示されるように実装すれば良いでしょうか？

I want to do it✋
Should I implement it so that the image design screen is displayed when the Stamp menu is pressed?

**Comment by momomomo111** [comment]
@5altNaCl 
ありがとうございます！その認識で合っています 🙌

Thanks! Assigned! That's correct.
