### ISSUE TITLE
Implement transition effects for navigation

### ISSUE THREAD

**Issue by fornewid** [DroidKaigi/conference-app-2023#530]
**Idea Description**
Currently, the DroidKaigi app use default transitions for navigation between each screens.
We can improve transition effects according to Material Design's Motion Guidelines.

- NavHost (in **KaigiApp.kt**): [Fade through](https://m2.material.io/design/motion/the-motion-system.html#fade-through)
- NavHost (in **MainScreen.kt**): [Shared Axis](https://m2.material.io/design/motion/the-motion-system.html#shared-axis)

Actually I implemented an associative library that supports Compose Multiplatform.
(https://github.com/fornewid/material-motion-compose)

How do you think about this improvements?

**Reference images and links**
- Material Design - Motion Guidelines
   - M2: https://m2.material.io/design/motion/the-motion-system.html
   - M3: https://m3.material.io/styles/motion/transitions/transition-patterns
- Implementation References
   - Android View: https://github.com/material-components/material-components-android
   - Compose (+ Multiplatform): https://github.com/fornewid/material-motion-compose

**Comment by takahirom** [comment]
Sounds great!

**Comment by fornewid** [comment]
So can I do this?

**Comment by takahirom** [comment]
Go ahead! Thanks!

**Comment by takahirom** [comment]
Oh, let me think about the library 👀

**Comment by takahirom** [comment]
Will it be like this? Looks nice. 
https://fornewid.github.io/material-motion-compose/navigation/

**Comment by fornewid** [comment]
We can either use a library or not. :)
It's not difficult to implement without a library.
