### ISSUE TITLE
[Build] Run CodeQL

### ISSUE THREAD

**Issue by jmatsu** [DroidKaigi/conference-app-2023#54]
This is a proposal to introduce CodeQL. CodeQL is a discovery tool for vulnerabilities and can visualize them by some integrations.

- https://codeql.github.com/
- https://github.com/github/codeql-action

**Comment by tick-taku** [comment]
I wanna give it a try 🙋

**Comment by swimmy-reo** [comment]
thanks, please!! 🙇
