### ISSUE TITLE
Add a 'Read More' Button in TimetableItemDetailScreen for Long Descriptions

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#544]
### Problem Description
When the text in the TimetableItemDetailScreen is too long, it becomes challenging to read. To enhance user experience, we should provide a "Read More" button for extended descriptions.

### Suggested Solution
Implement a "Read More" button that allows users to expand and collapse the description text as needed. This will improve readability and navigation within the TimetableItemDetailScreen.

### Additional Context
This issue aims to enhance user interaction within the app, especially for long descriptions in the timetable. Contributions are welcome!

![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/5eebc8b4-cac3-4086-89de-f5859bd1bc59)

**Comment by JaesungLeee** [comment]
can i try this issue? 🙋‍♂️

**Comment by swimmy-reo** [comment]
yes, please !! 👍
