### ISSUE TITLE
Apply Simplified Design for Timetable Grid Items Without Speakers

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#547]
Idea Description
The design for timetable grid items without speakers (such as Welcome Talks) is currently the same as items with speakers. A more suitable design for speaker-less items is available in Figma and needs to be applied.

Reference images and links
Please refer to the following Figma link for the new design: https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI .
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/0b5354ea-7380-4f4a-a912-a6bc3f8b2bc6)

**Comment by Corvus400** [comment]
Can I work on this task?

**Comment by Corvus400** [comment]
@takahirom 
I have a question about hall colors! ✋
It seems that only the light theme is defined, not the light theme and the dark theme.
Is it OK to add the respective colors in this Issue?

## Screenshot
Light | Dark
:--: | :--:
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/dc3a85a8-f5d1-40cc-a917-48644821a4bc" width="300" /> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/a46716ca-0898-4ed4-aaed-d4437dd1040e" width="300" />

**Comment by takahirom** [comment]
>Is it OK to add the respective colors in this Issue?

That would be great! 🙏
