### ISSUE TITLE
Use App's Icon as Project Icon in Android Studio

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#549]
**Idea Description**
Our Android Studio project currently lacks a distinctive project icon. To maintain branding consistency and ease of identification, we propose using the app's existing icon as the project icon within Android Studio.

**Reference images and links**
The app's icon, which should be used for this purpose, can be found within the project's resources or at the following link if available: https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI

**Comment by maxfie1d** [comment]
Can I try this one?

**Comment by jmatsu** [comment]
Please go ahead. Thanks~
