### ISSUE TITLE
Add Placeholder Text to Search Field

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#550]
**Issue: Add Placeholder Text to Search Field**

**Idea Description**
The search field in the app currently lacks a placeholder to guide users. Adding the placeholder text "気になる技術を入力" (Enter a technology of interest) will provide users with a clear hint about what they should input, enhancing user experience.
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/abb5fada-862b-4443-9e2d-ed7471998a2a)
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI

**Comment by hiraike32** [comment]
Can I implement this issue?

**Comment by jmatsu** [comment]
Yes, please!
