### ISSUE TITLE
[iOS] Apply Gradient background for TimetableView

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#558]
**Idea Description**

- Current TimetableView background design in iOS isn't correct. Please apply correct design.

**Reference images and links**
| Current | Should be |
|--------|--------|
| <img width="455" alt="スクリーンショット 2023-08-16 20 17 49" src="https://github.com/DroidKaigi/conference-app-2023/assets/30540303/be82a45a-90b5-4208-91c8-369237d527d2"> | <img width="421" alt="スクリーンショット 2023-08-16 20 15 49" src="https://github.com/DroidKaigi/conference-app-2023/assets/30540303/fc0eb0a0-be63-4383-91d2-513282244d9c">|

**Comment by onakama** [comment]
🖐️

**Comment by mhidaka** [comment]
Thanks! We assigned you.👍
