### ISSUE TITLE
Update background color of the top area of the timetable screen.

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#560]
**Idea Description**
Please update background color of timetable screen so that we can align we figma.

**Reference images and links**
<img width="861" alt="スクリーンショット 2023-08-16 21 12 19" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/105b65d3-e0a6-4171-9886-af3af9d4e0e3">

**Comment by Masaki-U** [comment]
🙋 I'd like to try this issue!

**Comment by upon0426** [comment]
Thanks! Assigned you!

**Comment by Masaki-U** [comment]
@upon0426 
Hi!
Please check my PR.
