### ISSUE TITLE
Updated font size on session detail screen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#562]
**Idea Description**
As font size is not reflecting the latest figma update, we need to align to it.

**Reference images and links**

<img width="736" alt="スクリーンショット 2023-08-16 21 17 46" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/9837605e-8d5f-4b80-9d23-71007d0921b8">

**Comment by sanao1006** [comment]
🙋 I'd like to try this issue!

**Comment by upon0426** [comment]
Thanks,assigned you!
