### ISSUE TITLE
[iOS] Change social link button icon image 

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#565]
**Idea Description**

- Current social link button icon is not correct. Please apply latest one 🙏🏼 

**Reference images and links**

Current | Should be
--|--
<img width="455" alt="スクリーンショット 2023-08-16 22 26 24" src="https://github.com/DroidKaigi/conference-app-2023/assets/30540303/4bbc1314-e1dc-4ccf-b745-34db68b288f0">|<img width="490" alt="スクリーンショット 2023-08-16 22 26 16" src="https://github.com/DroidKaigi/conference-app-2023/assets/30540303/29c29052-e815-40bf-acc0-da1a148563d7">

**Comment by gibachan** [comment]
I'd like to take this issue 🙋
