### ISSUE TITLE
Specify color which can support with dark theme

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#567]
**Idea Description**
Update color information so that text color is proper even with dark theme

**Reference images and links**
<img width="890" alt="スクリーンショット 2023-08-16 22 31 21" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/9bdc9a85-e604-4c13-9201-d236d1557dbe">

**Comment by Corvus400** [comment]
Perhaps this Issue may be resolved once [this PR](https://github.com/DroidKaigi/conference-app-2023/pull/557) is merged.
