### ISSUE TITLE
Update font size for empty view of bookmark screen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#568]
**Idea Description**
Reflect latest design to update the size of font

**Reference images and links**
<img width="501" alt="スクリーンショット 2023-08-16 22 33 38" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/7d863de7-c2f4-42f1-8b3d-bea22c779296">

**Comment by matsuurayuki1219** [comment]
Can I take this issue ??

**Comment by mhidaka** [comment]
Sure, we welcome your contrib! I Assigned you. 👍
