### ISSUE TITLE
Use FilterChip for bookmark filter

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#570]
**Idea Description**
For more proper use of component, let's replace the chip from AssistChip to FilterChip

**Reference images and links**
<img width="400" alt="スクリーンショット 2023-08-16 22 39 46" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/509b3efd-4352-41b8-9858-fbe445a47a47">

**Comment by kumokumot** [comment]
🙋‍♂️can I try this issue?

**Comment by satsukies** [comment]
@kumokumot Nice! Assigned 👍
