### ISSUE TITLE
Room (ex. bumblebee, dolphin) colors are different from Figma

### ISSUE THREAD

**Issue by tfandkusu** [DroidKaigi/conference-app-2023#575]
**Describe the bug**

Room (Ex. Bumblebee, Dolphin) colors are different from Figma.

| Implementation | Figma |
| --- |  --- |
| <img src="https://github.com/DroidKaigi/conference-app-2023/assets/16898831/686590a0-2f65-4918-9bd8-0dec3bd1c76d" width="200"> | [Figma Link](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56081-60248&mode=design&t=PXv9x7fY3I8fwZEF-4) |

- I think room color must be correct because colors intend commonly imagined animal color.
- And room colors for dark theme is not set.

**To Reproduce**
1. Go to TimetableList
2. Bumblebee is green and Dolphin is brown.
3. Go to TimetableGrid
4. Chipmunk is purple.

**Expected behavior**
Room colors are same as Figma including dark theme.

**Screenshots**

Dark Theme

| Implementation | Figma |
| --- |  --- |
| <img src="https://github.com/DroidKaigi/conference-app-2023/assets/16898831/955b3179-793f-44e3-b62d-9a8c961445af" width="200"> | [Figma Link](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-49559&mode=design&t=PXv9x7fY3I8fwZEF-4) |

TimetableGrid
 
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/16898831/a5f4c946-e8f5-4714-a4f0-813d82ed7201" width="200">
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/16898831/80cd24c6-fb4f-4d1d-a1e5-3a913b1268cc" width="200">

A yellow session is on green animal's room.

**Comment by mangano-ito** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
