### ISSUE TITLE
Improve FloorMapUiState robustness

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2023#581]
**Idea Description**

[FloorMapUiState](https://github.com/DroidKaigi/conference-app-2023/blob/main/feature/floor-map/src/main/java/io/github/droidkaigi/confsched2023/floormap/section/FloorMap.kt) has a integrity vulnerability.
We can create a incongruous instance such as `FloorMapUiState(FloorLevel.Basement, R.drawable.img_floormap_ground)` (basement floor name, but ground floor image), because FloorMapUiState has public constructor.
It should be modified to a design that cannot create the wrong instance.

**Implementation Idea**

```kotlin
// sealed interface + object(singleton)
sealed interface FloorMapUiState {
    val floorName: String
    @get:DrawableRes val floorMapResId: Int
                                                                          
    data object Basement : FloorMapUiState {
        override val floorName: String = FloorLevel.Basement.name
        override val floorMapResId: Int = R.drawable.img_floormap_basement
    }
                                                                          
    data object Ground : FloorMapUiState {
        override val floorName: String = FloorLevel.Ground.name
        override val floorMapResId: Int = R.drawable.img_floormap_ground
    }
                                                                          
    companion object {
        fun of(floorLevel: FloorLevel): FloorMapUiState {
            return when (floorLevel) {
                FloorLevel.Basement -> Basement
                FloorLevel.Ground -> Ground
            }
        }
    }
}
```

Anyone has a better idea?

**Comment by takahirom** [comment]
Looks great!

**Comment by l2hyunwoo** [comment]
@mikanIchinose It seems like a `private` modifier to the constructor would be sufficient.

**Comment by mikanIchinose** [comment]
> It seems like attach private modifier to the constructor would be sufficient.

Thank you for your idea.
However data class generates `copy` method..
It acts the same as the public constructor.
So the way of creating the wrong instance will remain.

```kotlin
data class FloorMapUiModel private constructor(
  private val flooLevel: FloorLevel,
  @DrawableRes val floorMapResId: Int,
) {
  // ...
}

val uiState = FloorMapUiState.of(FloorLevel.Basement)
val newUiState = uiState.copy(floorMapResId = R.drawable.img_floormap_ground)

// uiState is correct instance.
// But newUiState is wrong instance.
```

**Comment by l2hyunwoo** [comment]
@mikanIchinose Or it can implemented with enum class! 

I think if floorName and floorMapResId is constant, it could be considered to constant(technically, object act like constant). So it could be implemented with below code.

```kotlin
enum class FloorMapUiState(
    val floorLevel: FloorLevel,
    val floorName: String,
    @DrawableRes val floorMapResId: Int
) {
    Basement(FloorLevel.Basement, FloorLevel.Basement.name, R.drawable.img_floormap_basement),
    Ground(FloorLevel.Ground, FloorLevel.Ground.name, R.drawable.img_floormap_ground);

    companion object {
        fun of(floorLevel: FloorLevel) = values().find { it.floorLevel == floorLevel } ?: throw IllegalStateException("There's no such floorLevel $floorLevel")
    }
}
```

**Comment by mikanIchinose** [comment]
Reasonable idea!!

**Comment by l2hyunwoo** [comment]
@mikanIchinose @takahirom Can I refactor it with above design?

**Comment by takahirom** [comment]
@l2hyunwoo Looks great! Go ahead!

**Comment by mikanIchinose** [comment]
@l2hyunwoo No Problem. Let you refactor!!
