### ISSUE TITLE
Update basement floor map image.

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2023#584]
**Idea Description**

Implementation | Figma(2023/08/17)
:--: | :--:
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/29175998/b41b03b4-3c43-4b31-b971-fbbd7ae7cd3d" width="300" /> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/29175998/1ffab360-3f97-4f0b-9d67-a216dbbdfd9d" width="300" />

**Comment by pvcresin** [comment]
@mikanIchinose 🙋 I'd like to try this issue!

**Comment by takahirom** [comment]
Thanks! Assigned!
