### ISSUE TITLE
Update Switcher Background Color for Dark Mode Support

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#591]
**Idea Description**
Update Switcher Background Color for Dark Mode Support

**Reference images and links**
<img width="991" alt="スクリーンショット 2023-08-17 10 01 30" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/8a3a0e28-1fc0-4035-9b20-112396ad72d5">

**Comment by Corvus400** [comment]
May I work on this task?
