### ISSUE TITLE
Escape compare report '#' to see the changes

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#592]
**Idea Description**

https://github.com/DroidKaigi/conference-app-2023/blob/4e760ba1fe2fbe7a8f078108eb61af62835858ff/.github/workflows/CompareScreenshotComment.yml#L116

Snapshot diff report
| File name | Image |
|-------|-------|
| [KaigiAppTest.checkNa<br>vigateToSearchShot_c<br>ompare.png](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/#550_add_search_placeholder/./screenshot-diff/app-android/build/outputs/roborazzi/KaigiAppTest.checkNavigateToSearchShot_compare.png) | ![](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/#550_add_search_placeholder/./screenshot-diff/app-android/build/outputs/roborazzi/KaigiAppTest.checkNavigateToSearchShot_compare.png?raw=true) |
| [io.github.droidkaigi<br>.confsched2023.sessi<br>ons.component_null_D<br>efaultGroup_SearchTe<br>xtFieldAppBarPreview<br>_0_null_compare.png](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/#550_add_search_placeholder/./screenshot-diff/app-android/build/outputs/roborazzi/io.github.droidkaigi.confsched2023.sessions.component_null_DefaultGroup_SearchTextFieldAppBarPreview_0_null_compare.png) | ![](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/#550_add_search_placeholder/./screenshot-diff/app-android/build/outputs/roborazzi/io.github.droidkaigi.confsched2023.sessions.component_null_DefaultGroup_SearchTextFieldAppBarPreview_0_null_compare.png?raw=true) |

↓
`# -> %23`

Snapshot diff report
| File name | Image |
|-------|-------|
| [KaigiAppTest.checkNa<br>vigateToSearchShot_c<br>ompare.png](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/%23550_add_search_placeholder/./screenshot-diff/app-android/build/outputs/roborazzi/KaigiAppTest.checkNavigateToSearchShot_compare.png) | ![](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/%23550_add_search_placeholder/./screenshot-diff/app-android/build/outputs/roborazzi/KaigiAppTest.checkNavigateToSearchShot_compare.png?raw=true) |
| [io.github.droidkaigi<br>.confsched2023.sessi<br>ons.component_null_D<br>efaultGroup_SearchTe<br>xtFieldAppBarPreview<br>_0_null_compare.png](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/%23550_add_search_placeholder/./screenshot-diff/app-android/build/outputs/roborazzi/io.github.droidkaigi.confsched2023.sessions.component_null_DefaultGroup_SearchTextFieldAppBarPreview_0_null_compare.png) | ![](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/%23550_add_search_placeholder/./screenshot-diff/app-android/build/outputs/roborazzi/io.github.droidkaigi.confsched2023.sessions.component_null_DefaultGroup_SearchTextFieldAppBarPreview_0_null_compare.png?raw=true) |

**Reference images and links**

**Comment by naotama2002** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Maybe it will be main branch workflow so you have to chech after merge🙏
