### ISSUE TITLE
Bookmark snackbar's "View" button doesn't work

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#609]
**Idea Description**

We would like to see the BookmarkScreen when we click it.
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/c9b94eb2-d6b8-4a52-848b-def803294ba8)

**Reference images and links**

**Comment by nemo-855** [comment]
🤚

**Comment by momomomo111** [comment]
@nemo-855  Thanks! Assigned!

**Comment by nemo-855** [comment]
I think my late response was the cause of this, but the contents of the assigned issue's response were already implemented in [another pull request](https://github.com/DroidKaigi/conference-app-2023/pull/908). What should I do in this case?

If necessary, I will temporarily hand over this issue to the person in charge of the pull request ↑.

**Comment by takahirom** [comment]
@nemo-855 I think the PR's implementation is for a different screen so it is not related to this 👀

**Comment by nemo-855** [comment]
@takahirom 
I was mistaken! Now, I will be in charge of this issue as originally planned.
