### ISSUE TITLE
Unable to open the project using the latest IntelliJ IDEA (2023.2.1 Preview)

### ISSUE THREAD

**Issue by atsushieno** [DroidKaigi/conference-app-2023#612]
We cannot load the entire project using IntelliJ IDEA 2023.2.1 Preview (same goes for 2023.2 Stable):

> The project is using an incompatible version (AGP 8.1.0) of the Android Gradle plugin. Latest supported version is AGP 8.1.0-dev

To my understanding, this Multiplatform project is configured to make it possible, not just to load on the latest Android Studio. (If it is not the case, then skip this.)

Reverting this commit fixes the issue: https://github.com/DroidKaigi/conference-app-2023/commit/02d5f5f5f18ca79750a8653772233a8f1a899488

**Comment by mhidaka** [comment]
Thank you for your information. This is a very useful point because many developers always want to use the new one. 
We welcome fixing action and would like to cooperate on this issue 👍

**Comment by atsushieno** [comment]
okay let me shoot it

**Comment by takahirom** [comment]
We may be able to use 8.1 rc or wait a little 👀 It seems like they are going to support 8.1 👀 
https://youtrack.jetbrains.com/issue/IDEA-326579/Support-for-AGP-8.1

**Comment by atsushieno** [comment]
We will be definitely able to use it in the near future. The question is how near, and whether that affects any iOS related development or not, due to the absolute deadline in your team.

But anyhow, what I wanted is to let you folks know the issue. How you deal with it is a different matter. I have almost no problem with this, I keep local changes.

**Comment by takahirom** [comment]
I think 23.2.2 is released so let me close this 🙏 
https://youtrack.jetbrains.com/articles/IDEA-A-2100661508/IntelliJ-IDEA-2023.2-Latest-Builds
