### ISSUE TITLE
Change label of Badges item in BottomNavigationBar to Stamps

### ISSUE THREAD

**Issue by 5altNaCl** [DroidKaigi/conference-app-2023#613]
**Idea Description**
The badges have changed to stamps, but the labels of the badge items in the BottomNavigationBar have not changed.
Therefore, it needs to be changed as shown in [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?node-id=55416%3A70957&mode=dev).

**Reference images and links**
- [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?node-id=55416%3A70957&mode=dev)
![image](https://github.com/DroidKaigi/conference-app-2023/assets/29651972/de8f5d96-281b-4fc5-82ec-97f7fb0f075e)

**Comment by tatsuyafujisaki** [comment]
🙋

**Comment by momomomo111** [comment]
@tatsuyafujisaki Thanks! Assigned!
