### ISSUE TITLE
Let me use the app in Japanese on my English system

### ISSUE THREAD

**Issue by atsushieno** [DroidKaigi/conference-app-2023#618]
**Idea Description**

Android 13 makes it possible for us to choose the language we want to use for each app. The feature is however opt-in and we have to make minor changes in the app. My Android device defaults to English, but since the majority of those sessions are in Japanese and the session titles are most likely determined in Japanese first, I would like to run it in Japanese mode.

I have a patch that makes it.

**Reference images and links**

https://developer.android.com/guide/topics/resources/app-languages

**Comment by takahirom** [comment]
Looks great!

**Comment by takahirom** [comment]
Will you do it?

**Comment by atsushieno** [comment]
cooking a PR now!
