### ISSUE TITLE
Replace Loading string during loading with TimetableItemDetailScreen

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#621]
**Idea Description**
Please replace the 'Loading' text on the TimetableItemDetailScreen with something else that indicates it is loading, such as a progress bar.

**Reference images and links**
<img width="300" alt="Loading" src="https://github.com/DroidKaigi/conference-app-2023/assets/51113946/918c79e4-79eb-41f5-9154-2512c100b3de">

**Comment by matsumo0922** [comment]
I would like to challenge this issue!

**Comment by tkhs0604** [comment]
@matsumo0922 
Thank you for your challenge! Assigned!
