### ISSUE TITLE
Fix Non-Functional Add to Google Calendar Button on TimetableItemDetailScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#622]
**Idea Description**
Fix the non-functional button that adds sessions to Google Calendar on the TimetableItemDetailScreen.

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/c60fe426-67de-4d72-b37e-0e4578a049d4)

**Comment by tarumzu** [comment]
I'd like to try this issue!

**Comment by takahirom** [comment]
Thanks as always! Assigned!
