### ISSUE TITLE
Use pascal case instead of snake case

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#623]
**Idea Description**
Please use pascal case for those const values here.
https://github.com/DroidKaigi/conference-app-2023/pull/519/files#diff-eb541caab1535b5af692b5b9cd3804dd961c0170bdbff6f470e875701e54739dR22-R25

**Reference images and links**
Here is the referrence:
[https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md#singletons-constants-seal[…]ass-and-enum-class-values](https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md#singletons-constants-sealed-class-and-enum-class-values)

**Comment by iroha-168** [comment]
I'd like to work on this!!

**Comment by upon0426** [comment]
Thanks! Assigned you!

**Comment by 5altNaCl** [comment]
First time I've know of this!
I didn't know, I've increased it as it is [here](https://github.com/DroidKaigi/conference-app-2023/blob/cd33a36cfba03b0001967a86662802cb012b87bf/feature/stamps/src/main/java/io/github/droidkaigi/confsched2023/stamps/section/StampsList.kt#L17-L19)...
#541 

@iroha-168 
Would you please change this as well.

**Comment by iroha-168** [comment]
@5altNaCl 
I see! Thank you!!
