### ISSUE TITLE
Add Screenshot Test for Changing Floors on Floor Map

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#624]
**Idea Description**
Implement a screenshot test to verify the functionality of changing floors on the Floor Map.

https://github.com/DroidKaigi/conference-app-2023/blob/main/feature/floor-map/src/test/java/io/github/droidkaigi/confsched2023/FloorMapScreenTest.kt#L35

**Reference images and links**
<img width="291" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/591e94a4-3ad0-4b7f-873a-4837e79a4ddd">

**Comment by maxfie1d** [comment]
Can I try this one?

**Comment by upon0426** [comment]
Sure! Go ahead!
