### ISSUE TITLE
Define the color of the Mark on the FloorMap

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#625]
**Idea Description**
Please make it easier to add events by defining the colors of the markers on the Floor Map.

**Reference images and links**
<img width="300" alt="Floor Map" src="https://github.com/DroidKaigi/conference-app-2023/assets/51113946/70709634-289a-40c5-899e-58ecb0701a20">

**Comment by takahirom** [comment]
We can refer to the mark colors in figma.

**Comment by ErikoStoo** [comment]
🙋

**Comment by upon0426** [comment]
Sure! Go ahead!
