### ISSUE TITLE
Simplify the change of state when ReadMoreOutlinedButton is clicked

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#626]
**Idea Description**
When we click the ReadMoreOutlinedButton, we check its current state to change the value. However, it might be simpler to just set it directly to `false`

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/blob/c27309eab4f5a252f8c282e6e667eabe2b9c4ee2/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableItemDetailContent.kt#L95

**Comment by sanao1006** [comment]
🙋

**Comment by momomomo111** [comment]
@sanao1006 Thanks! Assigned!

**Comment by sanao1006** [comment]
@momomomo111 
```kotlin
onClick = { isExpanded = true }, 
```
Is it OK to recognize that tapping the button changes isExpanded to true as above (because if isExpanded = false, the expanded text will not be displayed).
ボタンをタップすると、上記のようにisExpandedをtrueに変えるという認識でOKでしょうか（`isExpanded = false`の場合、展開されたテキストは表示されないため）。

**Comment by takahirom** [comment]
Yes, you are right!
isExpanded = true is exactly what we want to do!

**Comment by sanao1006** [comment]
Thanks for the reply! I will create a PR right away!
