### ISSUE TITLE
Improved method of retrieving version names

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#628]
**Idea Description**
I need to fetch the version name every time a Composable function is re-drawn, and I'd like to improve performance in some way. I'd appreciate any good ideas you might have (e.g., using the remember{} method).

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/blob/efc6880ff10f3aa27a7037e803b899730a0290c5/feature/about/src/main/java/io/github/droidkaigi/confsched2023/about/AboutScreen.kt#L65

**Comment by matsumo0922** [comment]
I want to try this issue ✋

**Comment by sobaya-0141** [comment]
Thanks! Assigned!
