### ISSUE TITLE
Add Screenshot Test for Search Screen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#629]
**Idea Description**
Implement a screenshot test to verify the functionality of search screen.
Just checking the launch of the app is above acceptant criteria. But you can implement more actions if you want.

**Reference images and links**
<img width="479" alt="スクリーンショット 2023-08-17 20 32 58" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/8d5159d7-0017-4378-999f-330ec1ca328a">

**Comment by Corvus400** [comment]
I would like to try this one!

**Comment by takahirom** [comment]
Thanks! I'm looking forward to your pr!
