### ISSUE TITLE
Add Screenshot Test for expansion of time table detail screen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#630]
**Idea Description**
Implement a screenshot test to verify the functionality of expansion of time table detail screen.

**Reference images and links**
<img width="352" alt="スクリーンショット 2023-08-17 20 56 38" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/792c7659-9971-4f44-bbee-fdb3041a424c">

**Comment by Tounyu** [comment]
Can i try this? 🙋

**Comment by upon0426** [comment]
Sure! Go ahead!
