### ISSUE TITLE
Update SnackbarHostState Initialization with remember Function

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#631]
**Idea Description**

Replace the current initialization of val snackbarHostState = SnackbarHostState() with val snackbarHostState = remember { SnackbarHostState() }. This change is aimed at following proper state management within the component.

```
val snackbarHostState = SnackbarHostState()

↓

val snackbarHostState = remember { SnackbarHostState() }
```

**Reference images and links**
https://developer.android.com/reference/kotlin/androidx/compose/material3/SnackbarHostState#showSnackbar(androidx.compose.material3.SnackbarVisuals)

**Comment by takarabe-hamuyatti** [comment]
🙋

**Comment by takahirom** [comment]
Thanks Assigned 👍
