### ISSUE TITLE
Add Screenshot Test for transition of days

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#632]
**Idea Description**
Implement a screenshot test to verify the functionality of transition from day to day

**Reference images and links**

https://github.com/DroidKaigi/conference-app-2023/assets/45708639/3f972c96-6fab-4cfc-bca2-16b0d513aa8c

**Comment by maxfie1d** [comment]
Can I try this one?

**Comment by takahirom** [comment]
@maxfie1d Sorry for being late! Assigned!

**Comment by takahirom** [comment]
@maxfie1d  I hope all is going well. Would you have some time to update me on how this issue is progressing?

**Comment by takahirom** [comment]
@maxfie1d Let me unassign this since I couldn't get response 🙇

**Comment by Corvus400** [comment]
@takahirom 
I would like to receive this task.🙋

**Comment by takahirom** [comment]
@Corvus400 Thanks as always! Assigned 👍
