### ISSUE TITLE
Add Preview to TimeTableItemDetailScreen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#635]
**Idea Description**
Add Preview to TimeTableItemDetailScreen

**Reference images and links**
<img width="171" alt="スクリーンショット 2023-08-17 21 11 54" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/bc76c74a-1e52-4f5b-afd4-e756347d5b6f">

**Comment by takahirom** [comment]
Thanks! Assigned 👍
