### ISSUE TITLE
Scroll till bottom of the screen in screen shot test of badge screen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#641]
**Idea Description**
Implement scroll function in screen shot test of badge screen

**Reference images and links**
<img width="219" alt="スクリーンショット 2023-08-17 22 01 52" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/cf4ca34c-3375-437f-b80e-23377323b6c9">

**Comment by tfandkusu** [comment]
🙋

**Comment by upon0426** [comment]
Thanks!Assigned you!
