### ISSUE TITLE
Set end padding to title of the timetable item detail screen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#642]
**Idea Description**
Put padding to the end of title description in time able item detail screen

**Reference images and links**
As-is | To-be
:--: | :--: 
<img width="261" alt="スクリーンショット 2023-08-17 22 20 23" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/d675cc10-1d11-44a6-9460-babb8c015624"> | <img width="378" alt="スクリーンショット 2023-08-17 22 12 22" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/f043af0e-bef9-4a5d-a516-5827fa53f150">

**Comment by hiwa0** [comment]
Can I try this issue?🙋

**Comment by takahirom** [comment]
Please try it!
