### ISSUE TITLE
Add blur effect around switcher

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#643]
**Idea Description**
Implement blur container with gradation around switcher

**Reference images and links**
<img width="196" alt="スクリーンショット 2023-08-17 22 49 30" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/342a6ce3-e08e-4595-82dd-44f1222d3364">

**Comment by taratara10** [comment]
Can I try this issue?🙋

**Comment by upon0426** [comment]
Sure! Go ahead!
