### ISSUE TITLE
Add side event information of Ground floor

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#644]
**Idea Description**
Add event information according to figma

**Reference images and links**
As-is | To-be
:--: | :--:
<img width="319" alt="スクリーンショット 2023-08-17 22 59 37" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/bca27e35-1df2-4409-b495-f81d66ac90cb"> | <img width="319" alt="スクリーンショット 2023-08-17 22 59 37" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/5ca21db8-565b-48c3-b610-141de7ea6f2e">

**Comment by takahirom** [comment]
Thanks! Assigned 👍
