### ISSUE TITLE
Implement navigation to url of side event

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#645]
**Idea Description**
Implement onSideEventClick event. Please open with chrome custom tab following existing implementation.

**Reference images and links**
<img width="343" alt="スクリーンショット 2023-08-17 23 11 08" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/e5143355-6f67-48d9-ba15-0fac9b9d2e2f">

**Comment by umsys** [comment]
Can i try this issue? 🙋‍♂️

**Comment by upon0426** [comment]
Sure! Go ahead!
