### ISSUE TITLE
FloorMapSideEventItem should accept image if exists

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#646]
**Idea Description**
Update FloorMapSideEventItem so that it can to show image if exists.

**Reference images and links**
<img width="348" alt="スクリーンショット 2023-08-17 23 13 53" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/1fb015ca-4d7c-496c-b50f-31c0fe3b5efb">

**Comment by matsumo0922** [comment]
✋

**Comment by momomomo111** [comment]
@matsumo0922 Thanks! Assigned!
