### ISSUE TITLE
Animate the description when press the Read More button in TimetableItemDetailContent

### ISSUE THREAD

**Issue by matsumo0922** [DroidKaigi/conference-app-2023#655]
**Idea Description**
- In `TimetableItemDetailContent`, I want to add an animation when the `Read More` button is pressed.
  - Off-course no problems at present, but there is room for improvement in terms of user experience
  - Perhaps just add `animateContentSize`

**Comment by matsumo0922** [comment]
I'll be making PR in tomorrow, so please assign me.

**Comment by momomomo111** [comment]
@matsumo0922 Thank you! We appreciate you taking the lead.
