### ISSUE TITLE
App widget to show something

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#668]
**Idea Description**
We have a Jetpack Glance library to create a widget.
Is there any idea to use it?

I have these ideas. Do you have any ideas?

* Show a random session to recommend
* Show the date to the DroidKaigi day
* The next session we will have (for the DroidKaigi day) 

**Reference images and links**

**Comment by Naoki-Hidaka** [comment]
How about displaying a countdown until the date of the event?

**Comment by maxfie1d** [comment]
How about shortcuts widget for most frequent used features eg. floor map, stamps, bookmarks

**Comment by Corvus400** [comment]
I have never made a widget before, so I am very anxious, but I am willing to give it a try! 🙋
Is one of the ones you listed above what I should display?

**Comment by Noddy20** [comment]
The third idea (`The next session we will have (for the DroidKaigi day)`) combined with some summaries 
- Next session start count down
- Total talks of the current day (done/pending)

**Comment by Nanamare** [comment]
How about this feature?
* Bookmark sessions start count down(Time remaining)

**Comment by Corvus400** [comment]
@momomomo111 
Oops... sorry for the assignment, but it will probably be difficult to implement this task in the remaining days.🙇‍♂️
Please allow me to decline.🙇‍♂️

**Comment by momomomo111** [comment]
@Corvus400 
Sorry for the delayed response. 🙏
We have removed the assignment.

**Comment by takahirom** [comment]
Sorry, we couldn't have the design for this because of the workload. And we don't have time to implement. Let me close this for this year. We can use these ideas for the following year!
