### ISSUE TITLE
Navigate Contributors screen from about screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#669]
**Idea Description**
The title says everything

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/a73e8567-6b42-4a0f-b8d2-7fcca1b1f659)
https://github.com/DroidKaigi/conference-app-2023/blob/main/app-android/src/main/java/io/github/droidkaigi/confsched2023/KaigiApp.kt#L156C1-L156C38

**Comment by matsuurayuki1219** [comment]
Can I take this issue ??

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by matsuurayuki1219** [comment]
@takahirom 
This feature has been implemented...

**Comment by takahirom** [comment]
Oh.. sorry🙇

**Comment by takahirom** [comment]
We look forward to your anoter pr
