### ISSUE TITLE
Extract TimetableItemDetailContent section and create UiState for it

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#672]
**Idea Description**
The title says everything. Please refer to the link to see the implementation 

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/pull/652/files#diff-56fac00aca9688edbb218b72743e3ef63d925bfa243b61b3d2f7b59f3debb79cR140
https://github.com/DroidKaigi/conference-app-2023#section

**Comment by matsumo0922** [comment]
I want to try it.

**Comment by RyuNen344** [comment]
@matsumo0922 
Good! Assigned!
