### ISSUE TITLE
Is it allowed to request assignment for an issue that has not been taken action for a while?

### ISSUE THREAD

**Issue by katsu-gen** [DroidKaigi/conference-app-2023#675]
**Idea Description**
If it is allowed, Is it okay if it's about two weeks after the inactivity?
I apologize if it is inappropriate to ask a question here.

**Reference images and links**

**Comment by takahirom** [comment]
Thanks for your question.
I believe we have no choice but to assign others to make our conference app great when it seems that they are not working on it. Therefore, I think the answer is 'yes.'
