### ISSUE TITLE
Apply TimetableTopArea dark theme design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#676]
**Idea Description**
There is a new image for the dark theme. Please apply it!

**Reference images and links**
To be
<img width="322" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/0f1df869-52d3-443e-8b84-95221b0ac999">
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-56684&mode=dev

**Comment by Corvus400** [comment]
May I work on this task?

**Comment by takahirom** [comment]
Thanks! Assigned 👍
