### ISSUE TITLE
Apply AboutDroidKaigiDetail design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#679]
**Idea Description**
The image has been changed for the AboutDroidKaigiDetail for dark mode

**Reference images and links**
<img width="396" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/73d28bf9-c445-4308-a807-cf924c3b0518">

**Comment by ked4ma** [comment]
i want to do this :raised_hand_with_fingers_splayed:
