### ISSUE TITLE
Dark theme icon for Android Studio

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#681]
**Idea Description**
We have a dark theme icon in figma. So we can add dark theme icon for Android Studio!

**Reference images and links**
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?node-id=56197%3A19157&mode=dev

**Comment by ked4ma** [comment]
i'll do it :raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
Thanks!!

**Comment by ked4ma** [comment]
@takahirom 
Let me consult about this issue.
I set dark theme icon, it seemded reflected correctly.
But when I switch theme, app icon was not changed.
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/ca475924-3f13-4dbb-94d8-7186d62d6e71" width="300" />
I think it was same as conference-app-2022.
It would be better that apply only to splash screen?

※splash screen and process list and others are working correctly.

|Dark|Light|
|:-:|:-:|
|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/d1b3c4d8-884b-4b7f-b76c-6c6334bd7221" width="300"/> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/2db02a7a-8d21-4d51-8694-8f1e927eab84" width="300" /> |

[Screen_recording_20230818_223914.webm](https://github.com/DroidKaigi/conference-app-2023/assets/74723074/3d61b3af-11db-43dd-bf66-16d0d2b2262f)

**Comment by takahirom** [comment]
@ked4ma 
I mean like this.
https://github.com/DroidKaigi/conference-app-2023/pull/596
But I was surprised that we can use the dark color icon.
The reason icon doesn't change may be that the launcher app caches the icon.

**Comment by ked4ma** [comment]
@takahirom 
sorry, I noticed my misunderstanding just before you replied lol.
I'll do this again!!

> But I was surprised that we can use the dark color icon.

me too lol.

> The reason icon doesn't change may be that the launcher app caches the icon.

yeah, i think so too.
and google is saying they will NOT fix about this behavior.
(https://issuetracker.google.com/issues/147521650)

自分の早とちりで大変ご迷惑おかけしました :bow:

**Comment by takahirom** [comment]
You can set dark theme icon like this 🙏 
https://qiita.com/ryo_mm2d/items/ad60dfc8491bb57f3522#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E3%81%AE%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95

**Comment by ked4ma** [comment]
I didn't know it is possible to set images for both light and dark.
Thank you so much!
I'll fix pr.
