### ISSUE TITLE
Remove unused inner `testTag(TimetableGridItemTestTag) `

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#682]
**Idea Description**
The title says everything

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/blob/39a05eee778e7dd78efdacfd41746516f34f6aaa/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableGridItem.kt#L65-L70

**Comment by TonTonbow** [comment]
🙋‍♂️ 

I forgot... 🙇
