### ISSUE TITLE
Implement Test Coverage Measurement

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#684]
Idea Description
While test coverage might not directly reflect the quality of tests, it's essential to ensure that tests exist at least to a minimal degree. We want to implement a method to measure test coverage within our project, possibly using tools like kotlinx-kover. The goal is to find an effective way to gauge our test coverage and help guide future testing efforts.

Reference images and links

**Comment by tfandkusu** [comment]
I tried to output coverage report using jacoco plugin, but I could not find method for this project.

Project's build.gradle.kts

```kt
allprojects {
    apply(plugin = "jacoco")
}

tasks.register("jacocoReport", JacocoReport::class.java) {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    val mySourceDirectories = subprojects.map { project ->
        "${project.projectDir}/src/main/java"
    }
    val myClassDirectories = subprojects.map { project ->
        "${project.buildDir}/tmp/kotlin-classes/debug"
    }
    val execFileTree = fileTree(rootDir) {
        include("**/testDebugUnitTest.exec")
    }
    sourceDirectories.setFrom(mySourceDirectories)
    classDirectories.setFrom(myClassDirectories)
    executionData.setFrom(execFileTree)
}
```

```sh
./gradlew recordRoborazziDebug
./gradlew jacocoReport
```

![スクリーンショット 2023-08-19 15 51 44](https://github.com/DroidKaigi/conference-app-2023/assets/16898831/a83600a2-6d8d-4111-bd31-4b62294ba7aa)

**Comment by Tlaster** [comment]
I've just added kover support to the project and it works by `./gradlew koverHtmlReportRelease`, but not work for the app module, you can checkout [here](https://github.com/DroidKaigi/conference-app-2023/pull/746)
