### ISSUE TITLE
Apply AboutDroidKaigiDetail dark theme design

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2023#686]
**Idea Description**
I checked the other parts of the site to see if there were similar changes to #676, and found that AboutDroidKaigiDetail also had the same changes, so I created an Issue.

**Reference images and links**
To be
![image](https://github.com/DroidKaigi/conference-app-2023/assets/13657682/b79f0379-a21d-4a6f-a310-4e77b5aeca08)
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56147-41180&mode=dev

**Comment by takahirom** [comment]
I'm afraid. There is an issue for it. 😄 
https://github.com/DroidKaigi/conference-app-2023/issues/679
