### ISSUE TITLE
[Android] Incorrect wording that explains supported languages in English

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#696]
**Describe the bug**
Incorrect wording that explains supported languages in English on timetable item detail screen.

**To Reproduce**
Just to open timetable item detail screen which provides English interpretation

**Expected behavior**
It should be displayed `Japanese (with English Interpretation)` instead.

**Screenshots**
Japanese | English
:--: | :--:
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/88330d3d-e1df-423c-8f17-d5516e2c5545" width="300"> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/a51a4af5-5222-4ee3-8d82-41b2fcf3d48f" width="300">

**Comment by ked4ma** [comment]
can i do this? :raised_hand_with_fingers_splayed:

**Comment by RyuNen344** [comment]
Ofcourse!! Assigned!!
