### ISSUE TITLE
Change Placeholder Image for Side Events

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#713]
**Idea Description**
The current placeholder image for side events features a person, and we want to replace it with something more suitable. The new placeholder could be an image that resembles a generic picture or something that conveys the essence of an event. This change will enhance the visual appeal and relevance of the placeholder for side events.

**Reference images and links**
![image](https://github.com/DroidKaigi/conference-app-2023/assets/1386930/f77f3f2e-0ad9-49b5-a752-c177f8cbfe05)

**Comment by Nagumo-7960** [comment]
🙋

**Comment by upon0426** [comment]
Thanks! Assinged!
