### ISSUE TITLE
Move StaffList to section package and create UiState for it 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#714]
**Idea Description**
The title says everything. Please refer to the link to see the implementation

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/pull/573/files#diff-f95c0fdb024dd1ca5894ef4feea0454991932ad3cbd7ee4280da742f06fd2c47R96
https://github.com/DroidKaigi/conference-app-2023#section

**Comment by kwmt** [comment]
I want to try this 🙋

**Comment by takahirom** [comment]
Thanks! Assigned!

**Comment by kwmt** [comment]
I would like to display a Progress to indicate the state of data retrieval. Do you have any design for this?

**Comment by takahirom** [comment]
We don't have it but we can refer to timetable item detail screen's implementation.
