### ISSUE TITLE
Add Accessibility Dump Screenshot Test to TimetableItemDetailScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#717]
**Idea Description**

Implement an accessibility dump screenshot test for the TimetableScreen using Roborazzi. The task involves:
   - Adding the `checkAccessibilityCapture()` method to the `TimetableItemDetailScreenRobot` class.
   - Implementing the `checkLaunchAccessibilityShot()` in the `TimetableItemDetailScreenTest` class.

Here's the code snippet for `TimetableItemDetailScreenRobot`:

```kotlin
fun checkAccessibilityCapture() {
    composeTestRule
        .onRoot()
        .captureRoboImage(
            roborazziOptions = RoborazziOptions(
                captureType = RoborazziOptions.CaptureType.Dump(
                    explanation = Dump.AccessibilityExplanation,
                )
            )
        )
}
```

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/pull/561

**Comment by uhooi** [comment]
🙋

**Comment by upon0426** [comment]
Thanks! Assigned!
