### ISSUE TITLE
Make the splash screen more cool

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2023#723]
**Idea Description**
We want to make the splash screen more cooler.

**Reference images and links**
- https://developer.android.com/develop/ui/views/launch/splash-screen
- https://github.com/DroidKaigi/conference-app-2022/issues/135

**Comment by upon0426** [comment]
As we want to provide nicer design, let me assign our designer for now.
But if someone want to take the issue though it's blocked for now, we welcome that!

**Comment by nobonobopurin** [comment]
I have created a splash screen animation in Animated Vector Drawable format, please also refer to [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=59334-44585&mode=design&t=SO7Mc3PwsEAdu3z2-4) and create a splash screen.　

[avd_anim.xml.zip](https://github.com/DroidKaigi/conference-app-2023/files/12446759/avd_anim.xml.zip)

**Comment by Corvus400** [comment]
Is this task still blocked?

**Comment by Corvus400** [comment]
@takahirom 
Yes, sir!
By the way, may I have this task myself? 👀

**Comment by takahirom** [comment]
@Corvus400 Of course! Thanks as always!

**Comment by Corvus400** [comment]
@takahirom @nobonobopurin 

Sorry if I am wrong.🙇‍♂️
I tried to implement it based on the previous year's implementation, but the splash icons and brand image images seem to have a larger image size than the previous year.
Could you please confirm that the design is in line with the Android splash screen content?🙇‍♂️


https://github.com/DroidKaigi/conference-app-2023/assets/13657682/f49ff20e-8438-450d-92ff-910717e12edf



<img width="640" alt="スクリーンショット 2023-09-02 20 48 19" src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/49671600-ad8b-4ef4-910e-14dc4f2f2c14">
<img width="640" alt="スクリーンショット 2023-09-02 20 49 06" src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/97b80300-c794-4de7-bd19-cbbfce6647a7">

**Comment by Corvus400** [comment]
(Probably a question to myself...?🤔)
I think it would be quickest to make the same size as last year.💁‍♂️

**Comment by takahirom** [comment]
Could you try a small size? If you have something like you have to change a lot, let me know 👀

**Comment by Corvus400** [comment]
@takahirom 
Hmmm...I tried to fix it myself but it was impossible to fix.🙇‍♂️
Simply setting width,height,viewportWidth,viewportHeight to 108 will cause the view to be displayed as shown in the attached video.
I would appreciate it if the designer could fix it.🙇‍♂️

https://github.com/DroidKaigi/conference-app-2023/assets/13657682/7ed01893-5d8f-4167-a57e-632b569a0969

**Comment by takahirom** [comment]
Maybe we should't change viewportWidth and viewportHeight. Because they are the canvas size 👀

**Comment by Corvus400** [comment]
@takahirom 
I specified 108dp for width and height only, but the splash screen still looks the same as the attached video.🙇‍♂️

**Comment by takahirom** [comment]
@nobonobopurin Do you have any idea?🙏

**Comment by Corvus400** [comment]
@nobonobopurin 
We would appreciate your help in revising the material.🙇‍♂️
We are currently unable to proceed with this task.😭

**Comment by nobonobopurin** [comment]
@Corvus400 @takahirom 
Sorry for the delay in confirmation 😔
The canvas size for the animation has been changed to 108 both vertically and horizontally 🙏🏻
[avd_anim_0906.zip](https://github.com/DroidKaigi/conference-app-2023/files/12537715/avd_anim_0906.zip)

**Comment by Corvus400** [comment]
@nobonobopurin 
Thank you for taking time out of your busy schedule to respond! 🙇 
Please let me check if it works properly with the material you provided! 🙇

**Comment by Corvus400** [comment]
@nobonobopurin @takahirom 

Unfortunately, it seems that the icon is still missing on the left and right sides. 😭
This is indeed changed in the commit here, but for some reason it does not appear to have changed from the previously attached video.
In order to verify the possibility that this implementation is incorrect, I added the material from the 2022 application and ran it to test it out, and was able to confirm that it is displayed correctly as in the attached video.
Please take a moment to check again that the size of the material follows the same rules as last year. :bow:

Light(2023) | Dark(2023)
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/be01ec36-7640-47f4-9566-72913ef367a0" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/7665be84-450c-4795-a831-cdec6091b688" width="300" >

Light(Use 2022 material) | Dark(Use 2022 material)
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/5bca7453-12db-4f5f-a2c5-07e0c4c52ef0" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/21ad166f-131f-467a-bba8-e79ce076ee2e" width="300" >

**Comment by takahirom** [comment]
I found we can change the size like this. This will be 50%. Could you do it 60%? We might have to adjust a little. 🙇 

```
        <vector
            android:name="vector"
            android:width="108dp"
            android:height="108dp"
            android:viewportWidth="216"
            android:viewportHeight="216">
            <group
                android:name="group"
                android:translateX="52"
                android:translateY="52"
                >
```

**Comment by Corvus400** [comment]
@takahirom 
Once I applied the code you suggested, it appears to be working well! 🥳

> Could you do it with 60%? We might have to adjust a little. 🙇

Sorry, what should the 60% number be for this...? 👀 
I'm very sorry for the increased number of exchanges, but could you please tell me about this part? 🙇 

Light | Dark
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/ebbc9e95-8193-4ac5-b115-8fb17e276bef" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/42018975-5e5f-4a76-8475-4834849970c4" width="300" >

**Comment by takahirom** [comment]
Maybe we should adjust the number to resize the image to 60%. In my implementation, the image size would become 50%  👀

**Comment by Corvus400** [comment]
@takahirom 

Am I correct in assigning a value of 60% of the Viewport size to width and height?
Right now it is 216 * 0.5 = 108dp, but if I change this to 216 * 0.6 = 130dp, I see the following.
Sorry if my interpretation is wrong. :bow: 

Light | Dark
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/5acb191b-c2c2-481d-ab51-aac5c34723c4" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/4b129068-77ca-4755-b53b-4d53c8d24d7b" width="300" >

**Comment by takahirom** [comment]
@Corvus400 I've talked to the designer and she said looks good! Could you commit?

**Comment by Corvus400** [comment]
@takahirom 
We have corrected it to 60% [here](https://github.com/DroidKaigi/conference-app-2023/pull/1050/commits/f5f91b37ff1ef0ecc30910165aeb80a3f242e921)!
Sorry for the long wait, PR is now available for review!

**Comment by Corvus400** [comment]
@takahirom 
Do you want to reopen this task because the PR has been Revert? :eyes:

**Comment by takahirom** [comment]
@Corvus400 That would be great! 🙏

**Comment by Corvus400** [comment]
@takahirom 
Since the operation to reopen is not possible under my authority, could you please reopen it for me? 🙇

**Comment by Corvus400** [comment]
@takahirom 
Sorry, I may have misunderstood. 🙇 
If you mean that once an Issue is closed, no one can open it, then I will create a new Issue.

**Comment by takahirom** [comment]
@Corvus400 I reopened this issue!Thanks

**Comment by Corvus400** [comment]
Since the event day is in two days, this task will be completed with the highest priority!🫡
(However, we will not be able to work on this task until after 6:00 p.m.🙇‍♂️)

**Comment by takahirom** [comment]
Thanks as always!

**Comment by Corvus400** [comment]
@takahirom 
Sorry for the delay. 🙇 
The material has been modified in Inkscape so that the splash screen icon now displays correctly on API 30 devices.🫡
