### ISSUE TITLE
Change the name from StampsList to StampList

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#726]
**Idea Description**
The name 'StampsList' implies a list that returns multiple data sets, so I suggest changing it to 'StampList'. What do you think?

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/blob/fae756b1935c29d0293cd0e8e7b2ece9ea6f0770/feature/stamps/src/main/java/io/github/droidkaigi/confsched2023/stamps/section/StampsList.kt#L21-L24

**Comment by takahirom** [comment]
Sounds great!

**Comment by upon0426** [comment]
That’s a valid point! Sounds good!

**Comment by momomomo111** [comment]
Please let me handle this as it is!🙋‍♂️

**Comment by upon0426** [comment]
Sure, go ahead!
