### ISSUE TITLE
Fix the speaker to the bottom.

### ISSUE THREAD

**Issue by shxun6934** [DroidKaigi/conference-app-2023#731]
**Idea Description**
Currently, the session grid items are rendered as shown in the image below.
We would like the speaker to be fixed on the bottom to match the Figma design.

**Reference images and links**
Figma | Actual
 :-: | :-:
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/23094546/57972c88-1251-42d1-a27d-1ee9599f46fb" width="300" /> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/23094546/11623ecf-0415-4630-bf59-332925ac638a" width="300" />

**Comment by upon0426** [comment]
Sounds valid idea! 👍

**Comment by Aniokrait** [comment]
Is this issue assigned? If not, can I try this one?

**Comment by upon0426** [comment]
Sure! Thank you for showing the interest! Assigned you!
