### ISSUE TITLE
Navigation to Code of conduct, Privacy policy

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#735]
**Idea Description**
Implement navigation of Code of conduct, Privacy policy

**Reference images and links**
UR 
Code of conduct: https://portal.droidkaigi.jp/about/code-of-conduct
Privacy policy: https://portal.droidkaigi.jp/about/privacy

**Comment by TonTonbow** [comment]
I don't know if I can do it, but I want to try.🙋

**Comment by upon0426** [comment]
You can refer existing implementation 👍 
I assigned you!
