### ISSUE TITLE
Implement sponsors list item click

### ISSUE THREAD

**Issue by tahia910** [DroidKaigi/conference-app-2023#740]
**Idea Description**
Handle the click listener on the sponsors list screen.
(Clicking an item will crash the app for now)

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/blob/4f4e26c3f072d7203a9b6b717c95c3ce0145a047/app-android/src/main/java/io/github/droidkaigi/confsched2023/KaigiApp.kt#L121-L128

<img src="https://github.com/DroidKaigi/conference-app-2023/assets/37906654/8f3fbd76-a887-4ce7-ac45-794b6207de8c" height="450">

**Comment by upon0426** [comment]
Sounds valid! Thank you for finding it!

**Comment by akari317017** [comment]
✋🏻

**Comment by upon0426** [comment]
Thanks! Assigned you!

**Comment by takahirom** [comment]
@akari317017  I hope all is going well. Would you have some time to update me on how this issue is progressing?

**Comment by akari317017** [comment]
@takahirom 
Sorry, I did not submit a pull request.

I submitted this. https://github.com/DroidKaigi/conference-app-2023/pull/1000
