### ISSUE TITLE
Put proper padding to the end of list in side event list

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#741]
**Idea Description**
Please put more padding to the screen end.

**Reference images and links**
<img width="185" alt="スクリーンショット 2023-08-19 15 49 18" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/f90ea0c0-d88e-456b-af81-d4037f847800">

**Comment by upon0426** [comment]
Likely line to modify:
https://github.com/DroidKaigi/conference-app-2023/blob/4f4e26c3f072d7203a9b6b717c95c3ce0145a047/feature/floor-map/src/main/java/io/github/droidkaigi/confsched2023/floormap/FloorMapScreen.kt#L139

**Comment by sisosyunya** [comment]
May I handle this issue?✋

**Comment by upon0426** [comment]
Sure! Go ahead!
