### ISSUE TITLE
Change the icon inside the AboutDroidKaigiDetailSummaryCard to Outlined.

### ISSUE THREAD

**Issue by organic-nailer** [DroidKaigi/conference-app-2023#743]
**Describe the bug**
The icon for the location inside the AboutDroidKaigiDetailSummaryCard is set to Filled. It would be nice to be changed to Outlined to match Figma.

**To Reproduce**
1. Go to About Page

**Expected behavior**
outlined place icon is used

**Screenshots**
- Figma
![image](https://github.com/DroidKaigi/conference-app-2023/assets/31440714/f15fa544-e96f-4544-8c9d-e54a40e811e5)

- Actual
![image](https://github.com/DroidKaigi/conference-app-2023/assets/31440714/36a23544-9e2a-4c7a-a4d4-0a014a5ac1e5)

**Comment by upon0426** [comment]
Sounds valid point! Thank you for finding this!

**Comment by organic-nailer** [comment]
Please let me handle this as it is!🙋‍♂️

**Comment by upon0426** [comment]
Sure! Go ahead!
