### ISSUE TITLE
Removal of duplicated code within the bottom navigation

### ISSUE THREAD

**Issue by Murayu0225** [DroidKaigi/conference-app-2023#744]
**Idea Description**
The section from 
https://github.com/DroidKaigi/conference-app-2023/blob/0ea0e39cd3dc2f2d07c97dea42b0b38601b9b6a2/feature/main/src/main/java/io/github/droidkaigi/confsched2023/main/component/KaigiBottomBar.kt#L36-L60 
contains duplicated code, and I would like to simplify it

**Comment by upon0426** [comment]
True! Thank you for refactoring idea! Sounds valid!

**Comment by Murayu0225** [comment]
Can I try this issue?

**Comment by upon0426** [comment]
Sure! Go ahead!
