### ISSUE TITLE
Crash when open contributors screen offline

### ISSUE THREAD

**Issue by ked4ma** [DroidKaigi/conference-app-2023#752]
**Describe the bug**
App will crash when you open contributors screen **offline**

**To Reproduce**
1. modify `DefaultRemoteConfigApi.getBoolean(...)` due to crashing by other issue (#734)
    ```kotlin
    actual override suspend fun getBoolean(key: String): Boolean {
     + try {
            firebaseRemoteConfig.fetchAndActivate()
     + } catch (exception: FirebaseException) {
     +     Log.e("DefaultRemoteConfig", exception.message, exception)
     + }
        return firebaseRemoteConfig[key]
    }
    ```
2. set device **offline**
3. launch app
4. go to contributors from bottom nav bar
5. crash app

**Expected behavior**
- Not crash.
- (show snackbar or some info to user)

**Screenshots**

https://github.com/DroidKaigi/conference-app-2023/assets/74723074/44e2bd5b-611b-48b2-8867-1f3c9109660b

**Comment by matsuurayuki1219** [comment]
@ked4ma 
Thank you for finding out the bug 😊
Are you going to fix this ??

If you don't think so, I want to fix this bug 👍

**Comment by ked4ma** [comment]
@matsuurayuki1219 
Please take it!

**Comment by matsuurayuki1219** [comment]
@ked4ma 
Thank you !!

@takahirom 
Please assign this issue to me 🙇

**Comment by takahirom** [comment]
🙆‍♀️

**Comment by matsuurayuki1219** [comment]
@takahirom 
I'm wondering what to do,  so will you help me ??  🙇

Now I'm fixing `ContributorsViewModel.kt`.
To handle exceptions in data layer and show snackBars, I want to refer to `UserMessageStateHolder` in ContributorsViewModel. ( like the below. )

<img width="800" src="https://github.com/DroidKaigi/conference-app-2023/assets/105269911/113c3c23-df1e-439b-b5a8-02403d730352"/>

However, I can' t refer to `UserMessageStateHolder`, so What should I do ??

**Comment by takahirom** [comment]
@matsuurayuki1219 
Sorry for being late. It is because ContributorsViewModel is in commonMain and UserMessageStateHolder is in `androidMain`. We might have to move UserMessageStateHolder to commonMain to refer to UserMessageStateHolder.

**Comment by matsuurayuki1219** [comment]
@takahirom 
Thank you for your comment !!
I see your point 👍

I tried to fix, but I'm not so familiar with KMM, so I didn't fix this problem ... 
( I moved `UserMessageStateHolder`, but I can't build the application ... )

So can I remove my assignment ... ??

**Comment by takahirom** [comment]
Of course! Thank you for your challenge!🙆‍♂️

**Comment by hoashi-akane** [comment]
🙋 Can I take the challenge?

**Comment by satsukies** [comment]
@hoashi-akane Sure! Go ahead!
