### ISSUE TITLE
Add Monochromatic Icon

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#755]
**Idea Description**
For Android 13 (API level 33), we can use Monochromatic Icon. Please apply it!

**Reference images and links**
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=57713-28823&mode=design&t=iH9C6vVMHbFFKiMf-0
<img width="657" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/389c1ab4-6a3b-4143-ab1b-d3df46edd968">

**Comment by Dai1678** [comment]
I will try this PR ✋

**Comment by RyuNen344** [comment]
thx! assigned!!
