### ISSUE TITLE
[Idea]: Replace lambda function to callable reference

### ISSUE THREAD

**Issue by RyuNen344** [DroidKaigi/conference-app-2023#757]
**Idea Description**

Why we should use callable reference instead of lambda function?
we don't wanna care about composition, but lambda function instantiate which has not same hash. 
`Composable` will compose when hashes of args is different, so `Composable` with lambda instance has many point to `re`compose.
callable reference has same hash when instance is equal, so it is good to jetpack compose user.

```kotlin
at Composable
fun Hoge(onClickFoo: () -> Unit)
```

before
```kotlin
Hoge(
    onClickFoo = {
        navController.navigateToBar()
    }
)
```

after
```kotlin
Hoge(
    onClickFoo = navController::navigateToBar
)
```

**Reference images and links**

https://kotlinlang.org/docs/reflection.html#callable-references

**Comment by Corvus400** [comment]
May I have this task?

**Comment by RyuNen344** [comment]
Ofcourse!! Assigned!!
