### ISSUE TITLE
Background color of BookmarkScreen is wrong in dark theme

### ISSUE THREAD

**Issue by S-H-Y-A** [DroidKaigi/conference-app-2023#764]
**Describe the bug**
Background color of BookmarkScreen is wrong in dark theme.

**To Reproduce**
1. Turn into dark theme.
2. Open BookmarkScreen

**Expected behavior**
Background color of BookmarkScreen should be black in dark theme.

**Screenshots**
![Screenshot_20230819_225432.png](https://github.com/DroidKaigi/conference-app-2023/assets/74596628/02bb17a4-abdc-458d-9211-e627d18f7f3f)

**Comment by takahirom** [comment]
Thanks!

**Comment by tkhskt** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
@tkhskt Thanks! Assigned!
