### ISSUE TITLE
[iOS][Idea] Add dynamic tab animation in timeline screen.

### ISSUE THREAD

**Issue by fumiyasac** [DroidKaigi/conference-app-2023#769]
**Idea Description**

In iOS app, the date selection doesn't displayed in the header View element was accompanied by an animation.
I think it would be better to add an animation when selecting a date like the Android app.

**Reference images and links**

<img src="https://github.com/DroidKaigi/conference-app-2023/assets/949561/f33d0ab1-d032-4619-b57d-ceca3438ac1e" width="390" />

**Comment by fumiyasac** [comment]
@RyuNen344 @takahirom 
Would you mind if I closed this issue?

**Comment by RyuNen344** [comment]
@fumiyasac 
yes, please 🙏
