### ISSUE TITLE
Shimmer effect CI unit test fails (does not finish).

### ISSUE THREAD

**Issue by sanao1006** [DroidKaigi/conference-app-2023#778]
**Describe the bug**
CI unit test fails due to `TimetableShimmerListItemPreview()` in TimetableShimmerListItem.kt. The test does not finish, times out and fails. Perhaps the test does not finish because it keeps waiting for the Shimmer Effect to finish animating.  

**Hint that may possibly lead to a solution**
  - takahirom found the following log (https://twitter.com/new_runnable/status/1692887907420479687)
  > "io.github.droidkaigi.confsched2023.sessions.component_null_Theme_TimetableShimmerListItemPreview-LightMode-8 _8_null"

**To Reproduce**
1.Uncomment TimetableShimmerListItemPreview() in TimetableShimmerListItem.kt
https://github.com/DroidKaigi/conference-app-2023/blob/2a774f0e97e4500603b9eda1148cfa3bfa57e8e5/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableShimmerListItem.kt#L70-L80
2.Running tests on Github Actions, and then they fail (tests may run fine on local).

**Expected behavior**
Simmer effect CI test passes without problems

**References**
- [Log of failed tests](https://github.com/DroidKaigi/conference-app-2023/actions/runs/5908387645/job/16027760011)
- #500
- #711 
- [ShimmerEffect library in use](https://github.com/valentinilk/compose-shimmer)

**Comment by takahirom** [comment]
You can check this by running PreviewTest.

**Comment by yamacraft** [comment]
I will try it. ✋ 
I have a feeling that the cause lies elsewhere.

**Comment by momomomo111** [comment]
@yamacraft 
Thanks! Assigned!

**Comment by yamacraft** [comment]
I felt that a fundamental solution seems impossible with just this project alone.

There's no doubt that the instantiation of `rememberShimmer()` is causing the UnitTest to halt. I suspect that the behavior of Robolectric itself, combined with the `MutableStateFlow` used in Shimmer, might be causing the `captureRoboImage` method in Roborazzi to continuously wait at `InstrumentationRegistry.getInstrumentation().waitForIdleSync()` .

In any case, covering this with just this project seems challenging. Therefore, as a temporary measure, I'll introduce an approach where we don't use Shimmer only when running Robolectric. With this, there's no need to give up on the Preview itself.

-----
【原文】
根本的な解決は、このプロジェクトだけでは不可能なように感じました。

`rememberShimmer()` のインスタンス生成でUnitTestが止まっているのは間違いないようです。
おそらくRobolectric自体の挙動と、Shimmer内で使われている `MutableStateFlow` が影響して、Roborazziの`captureRoboImage` にある `InstrumentationRegistry.getInstrumentation().waitForIdleSync()` で待ち続けているのではないかと推測しました。

なんにせよ、このプロジェクトだけでカバーするのは難しそうに感じます。
そのため、暫定的な対応になりますがRobolectricの時だけShimmerを利用しない対応方法を導入してみることにします。
これならPreviewそのものを諦める必要はなくなります。
