### ISSUE TITLE
[Bug][iOS] foregroundStyle is not reflected to icons

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#779]
**Describe the bug**
From #777. 
In case of the above PR, the bookmark icons' color is not changed although foregroundStyle is applied to them.
This is because icons' rendering mode in Assets folder is set as Default.

**To Reproduce**
Just to open the app.

**Expected behavior**
Icons are tinted correctly.

**Screenshots**
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/25a3e496-6372-4bd6-b101-b657ba4d0260" width="300">

**Comment by fumiyasac** [comment]
🙋

**Comment by tkhs0604** [comment]
@fumiyasac 
Thank you! Assigned!
