### ISSUE TITLE
Color of AboutScreen TopAppBar title is difficult to see when in dark mode

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#787]
**Describe the bug**
The color of the title of the TopAppBar in the AboutScreen is difficult to see when scrolling in dark mode

Perhaps the color of the following text.
The color of text when not scrolling is not defined, so it is not necessary to define a color.
https://github.com/DroidKaigi/conference-app-2023/blob/29922658fc76a516fec71ca2f498d021dc9d6dfb/feature/about/src/main/java/io/github/droidkaigi/confsched2023/about/AboutScreen.kt#L110-L114

**To Reproduce**
1. set to dark mode
2. go to AboutScreen
3. scroll down

**Expected behavior**
Titles are not the same color as the background, even in dark mode, and are easily visible.

**Screenshots**
|Dark mode|Light mode|
|---|---|
|<video src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/7019a37e-34c1-4ca4-a985-55ab3797a6b5">|<video src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/106c85f6-b4be-43ef-93a3-8e255c57d016">|

**Comment by ked4ma** [comment]
https://github.com/DroidKaigi/conference-app-2023/pull/772
i have submitted PR about this yesterday so let me link this issue to it.

**Comment by kosenda** [comment]
@ked4ma 
I apologize! I had overlooked it.
I will close this issue.

**Comment by ked4ma** [comment]
> @ked4ma I apologize! I had overlooked it. I will close this issue.

@kosenda 
thank you for your reply!
I set this to "close #ISSUE_NUMBER" of PR description.
so it will be closed automatically, if my pr is approved :smiley: 
![Screenshot from 2023-08-20 16-30-40](https://github.com/DroidKaigi/conference-app-2023/assets/74723074/0c37f8c0-887e-4b47-911f-5de58cbd9bd5)

**Comment by kosenda** [comment]
@ked4ma 
Thank you too!
I was repeatedly mistaken.
I will change the status to ReOpen!
