### ISSUE TITLE
Long session titles should be truncated with an ellipsis.

### ISSUE THREAD

**Issue by Aniokrait** [DroidKaigi/conference-app-2023#789]
**Idea Description**
Too long session titles should be truncated with an ellipsis to fit in the grid card like in [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-49893&mode=design&t=ACPg0PqDs2wfqfEp-4). However the long title pushes schedules and speakers out of the card and it fills all the space.

**Reference images and links**
| Current behavior | Expected bahavior |
| ---- | ---- |
| <img src="https://github.com/DroidKaigi/conference-app-2023/assets/43056135/96c04a33-21d2-41d0-9560-d66f26607f2c" width=300 /> | <img width="300" src="https://github.com/DroidKaigi/conference-app-2023/assets/43056135/8dde1cf3-28ef-4c4e-8429-5fec5eeaba8a"> |

https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-49893&mode=design&t=ACPg0PqDs2wfqfEp-4

**Comment by takahirom** [comment]
Well, as far as I know, we should use small text. Let me consult this with the designer

**Comment by takahirom** [comment]
I've checked.
We have to make it small by 12sp. And if it doesn't fit, we have to use `...`.

**Comment by Noddy20** [comment]
I can take this ✋🏻
Max lines should be 4?

**Comment by takahirom** [comment]
@Noddy20 
Thanks! 

> Max lines should be 4?

No, you shouldn't.

It will be a little logic. 😅 
This is just explanation code.

```kotlin
text.size = 14.sp
if(text.canFitInLayout) {
  return
}
sizeCandidate = calcFitLayout()
if(12 <= sizeCandidate) {
  text.size = sizeCandidate
  return
}
text.size = 12.sp
text.ellipsize = true
```
