### ISSUE TITLE
Hide searching text  when enable the BigFont/BigDisplay

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#790]
**Describe the bug**
Hide searching text  when enable the BigFont/BigDisplay

Applicable part
https://github.com/DroidKaigi/conference-app-2023/blob/66551e42d017d843da50ec9da26058d05cf002b4/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/SearchTextFieldAppBar.kt#L42

**To Reproduce**
1. enable the BigFont/BigDisplay
2. Go to Serach Screen

**Related Issues**
- #720 
- #464 

**Expected behavior**
Enabling BigFont/BigDisplay does not cause character broken

**Screenshots**
Phone: Pixel6
|Settings|Search Screen|
|---|---|
|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/4fffb039-0f3c-490a-a427-22d15301f9ec" width="300">|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/4ecfdb42-0132-4adc-8142-7b6232d14ea2" width="300">|

**Comment by jmatsu** [comment]
Thank you for your reporting. It has to be fixed.

**Comment by shinya-tan** [comment]
Can I take care of this issue?

**Comment by takahirom** [comment]
Thanks! Assigned 👍
