### ISSUE TITLE
Hide BookmarkFilterChip when enable the BigFont/BigDisplay

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#792]
**Describe the bug**
Hide BookmarkFilterChip when enable the BigFont/BigDisplay

I think that the following Row could be solved simply by making it a FlowRow.
https://github.com/DroidKaigi/conference-app-2023/blob/66551e42d017d843da50ec9da26058d05cf002b4/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkFilters.kt#L37

**To Reproduce**
1. enable the BigFont/BigDisplay
2. Go to Bookmark Screen

**Expected behavior**
All tips are displayed.

**Screenshots**
Phone: Pixel6
|Settings|Search Screen|
|---|---|
|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/4fffb039-0f3c-490a-a427-22d15301f9ec" width="300">|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/81316dcd-65aa-4448-9508-9c616770dc59" width="300">|

**Comment by takahirom** [comment]
FlowRow  is a one option but how about using a scrolling modifier?

**Comment by kosenda** [comment]
It sure looks better to have it scroll！
I would like to work on an implementation using the scroll modifier.

**Comment by RyuNen344** [comment]
@kosenda 
sorry for late 🙏 
assigned !

**Comment by kosenda** [comment]
Thank you very much for your time here !!

**Comment by kosenda** [comment]
It seemed to be complete with this issue.
https://github.com/DroidKaigi/conference-app-2023/issues/823

## Pixel6
https://github.com/DroidKaigi/conference-app-2023/assets/60963155/a14afc8f-1e54-4152-a18d-c8aa36c07788

**Comment by takahirom** [comment]
Thanks!
