### ISSUE TITLE
Make filters in bookmark scrollable

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#823]
**Idea Description**
Make scroll available for the filters in book mark screen

**Reference images and links**
You can see the right side chip is being bloken from screen shot test
https://github.com/DroidKaigi/conference-app-2023/pull/692#issuecomment-1684035996

**Comment by Hachimori** [comment]
🙋‍♂️

**Comment by RyuNen344** [comment]
💪 
assigned!!
