### ISSUE TITLE
Implement PreviewParameterProvider for the FloorLevelSwitcher

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#824]
**Idea Description**
Try introducing the PreviewParameterProvider

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/blob/788fb4f7f65a7aae4ee5d4773cf14bc7c33d8089/feature/floor-map/src/main/java/io/github/droidkaigi/confsched2023/floormap/component/FloorLevelSwitcher.kt#L111

**Comment by ked4ma** [comment]
Can I try this? :raised_hand_with_fingers_splayed:

**Comment by tkhs0604** [comment]
@ked4ma 
Thank you! Assigned!
