### ISSUE TITLE
Show multiple speaker icon when speaker is more than two

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#825]
**Idea Description**
Handle case with session with multiple speaker 

**Reference images and links**
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-49103&mode=dev
<img width="163" alt="スクリーンショット 2023-08-21 21 29 25" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/e31bd696-f538-4bd4-b15f-3799ba3eee8e">

You can remove this TODO comment once you finished implementation
https://github.com/DroidKaigi/conference-app-2023/blob/788fb4f7f65a7aae4ee5d4773cf14bc7c33d8089/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableGridItem.kt#L133

**Comment by ked4ma** [comment]
🖐️

**Comment by RyuNen344** [comment]
thanks!! Assigned!!
