### ISSUE TITLE
Replace `Chip` Design with Newly Defined `Tag`

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#826]
**Idea Description**
Currently, the Chip design is used in the application, and it comes with a constraint of having a larger tap target, preventing it from being resized smaller. To address this and embrace a new appearance with rounded corners, we need to replace the existing Chip design with the newly defined Tag. This change will allow for a more flexible and updated look within the application.

**Reference images and links**
<img width="319" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/d7beec8a-1610-44f3-bed1-567fc4fcb68f">

https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?node-id=54462%3A36316&mode=dev

**Comment by Hachimori** [comment]
🙋‍♂️

**Comment by Hachimori** [comment]
Let me confirm, but can I assume that the requirement is to change Chip's outline into the rounded corner?

**Comment by tkhs0604** [comment]
@Hachimori 
Thank you for asking us 🙇‍♂️
The answer is basically YES, but it would be appreciated if you could compare both designs and fill the gaps 🙏

Here are AS-IS and TO-BE designs: 
- AS-IS: https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-44515&mode=design&t=1dCLhvf2WD4lCYmV-0
- TO-BE: https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56145-45859&mode=design&t=1dCLhvf2WD4lCYmV-0

**Comment by tkhs0604** [comment]
> it comes with a constraint of having a larger tap target, preventing it from being resized smaller.

To resolve the above is another main point of the issue, so please take a look at it too 👍
