### ISSUE TITLE
The color of arrow to navigate up should be changed

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#827]
**Idea Description**
The color of arrow to navigate up will be transparent after scrolling

**Reference images and links**
<img width="608" alt="スクリーンショット 2023-08-21 21 36 23" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/7598d923-a64d-426e-a408-878caabd128c">

You can remove this TODO commends in this PR
https://github.com/DroidKaigi/conference-app-2023/blob/788fb4f7f65a7aae4ee5d4773cf14bc7c33d8089/feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/contributors/ContributorsScreen.kt#L69

**Comment by shinya-takano** [comment]
I think 'navigationIcon' is unnecessary.

Is this Fix ok? 'AboutScreen' is used as a reference.
```
navigationIcon = { }, // navigation Icon unnecessary
```

**Comment by shinya-takano** [comment]
🙋‍♂️

**Comment by momomomo111** [comment]
>I think 'navigationIcon' is unnecessary.
>Is this Fix ok? 'AboutScreen' is used as a reference.

@shinya-takano 
Thank you for noticing!
If the code can be simplified to match the Figma design, We'd be really happy!

**Comment by shinya-takano** [comment]
Oh, Contributor tab is unnecessary....Latest Figma!

https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54462-36316&mode=design&t=2oce2Zxj37mo7wqY-0

**Comment by shinya-takano** [comment]
Sorry, it takes a while..

or 

I think this issue can be closed.

**Comment by Hachimori** [comment]
🙋‍♂️

**Comment by Hachimori** [comment]
🙋‍♂️🙋‍♂️🙋‍♂️🙋‍♂️🙋‍♂️

**Comment by mhidaka** [comment]
@Hachimori Big thanks your comment and sorry for dely our reply. please try it 💪
