### ISSUE TITLE
Adjust Text Style of Speakers in Timetable to Match Figma Design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#828]
**Idea Description**
The text style of the speakers in the timetable needs to be adjusted to match the design specified in Figma. 

**Reference images and links**
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?node-id=54462%3A36316&mode=dev
<img width="848" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/612843cb-693e-4c84-b364-45a3b0db2349">

**Comment by momomomo111** [comment]
@KwakEuiJin 
Thanks! Assigned!
