### ISSUE TITLE
Set margin for the SideEventList only when screen end

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#829]
**Idea Description**
Mergin should be put only when screen end.

**Reference images and links**
When scrolling | When scrolled up
:--: | :--: 
<img width="300" alt="スクリーンショット 2023-08-21 21 44 58" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/e050dd54-0856-4ad7-a324-f92dd3a316bd"> | <img width="300" alt="スクリーンショット 2023-08-21 21 42 19" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/e13c13c3-31b3-4885-a453-7c63e1937143">

**Comment by Corvus400** [comment]
Can I have this task?

**Comment by takahirom** [comment]
Thanks! Assigned 👍
