### ISSUE TITLE
adjust margin around top android robot

### ISSUE THREAD

**Issue by RyuNen344** [DroidKaigi/conference-app-2023#830]
**Describe the bug**

| expect | actual |
| --- | --- |
|![2023-expect](https://github.com/DroidKaigi/conference-app-2023/assets/32740480/8027cbae-b1f5-4537-808f-ffc856e06862)|![Screenshot_20230821_214310](https://github.com/DroidKaigi/conference-app-2023/assets/32740480/f76bf8fd-9c5c-472c-9241-dbd551c9998a)|

**Comment by KwakEuiJin** [comment]
🙋‍♂️

**Comment by momomomo111** [comment]
@KwakEuiJin Thanks! Assigned!
