### ISSUE TITLE
Change Speaker Image Size in Timetable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#831]
**Idea Description**
Adjust the size of the speaker images in the timetable to match the design in Figma.

**Reference images and links**
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?node-id=57938%3A76457&mode=dev
<img width="653" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/92f667a0-a983-40a6-a397-dea9cffe9b92">

**Comment by Corvus400** [comment]
May I have this task?

**Comment by upon0426** [comment]
Sure! Assigned you!

**Comment by Corvus400** [comment]
@upon0426 
I have a quick question!🙋
In Figma, a size of 32x32 is specified, and it looks like there is no particular change from the current situation if I just specify that size.
Is this correct?🤔

Before | After
:--: | :--:
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/9e3066d2-38b3-4456-8d43-adca1d6a5cb1" width="300" /> | <img src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/d33595c8-4fab-4fc7-bc4d-bae2242b7870" width="300" />

**Comment by upon0426** [comment]
@Corvus400 
Thank you for confirmation!
In my understanding, the size of the icon used to be 40dp.
As we updated Figma, the size is shown 32dp. But in codebase, still the size is set 40dp.

Hope your question has answered properly.
Please feel free to ask further question if there are any unclear points!

**Comment by Corvus400** [comment]
I finally realized that I had confused TimetableGridItem with TimetableListItem after searching the code in the project in 40dp. 🙇‍♂️
Now that I understand which parts need to be corrected, I will start working on them!
