### ISSUE TITLE
Time in timetable should be aligned to center

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#833]
**Idea Description**
Time is not aligned to center.

**Reference images and links**
<img width="100" alt="スクリーンショット 2023-08-21 21 53 39" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/86feed37-cb13-4e3b-b1ca-d7921fc19766">

**Comment by matsumo0922** [comment]
I want to try this issue~

**Comment by swimmy-reo** [comment]
yes, please!! 👍
