### ISSUE TITLE
Color of text is wrong in timetable screen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#834]
**Idea Description**
The session end time should have different color

**Reference images and links**

<img width="139" alt="スクリーンショット 2023-08-21 22 03 04" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/4823b55a-8fc8-4b9a-9907-3634d0c44327">

**Comment by shinya-takano** [comment]
Fix textColor and fontWeight, OK?

<img width="676" alt="スクリーンショット 2023-08-22 0 38 29" src="https://github.com/DroidKaigi/conference-app-2023/assets/2821692/0d5c5de5-87aa-4219-ad96-1be7fb8fa363">

**Comment by CookieySun** [comment]
🙋‍♂️
