### ISSUE TITLE
Change TimetableListItem margin size

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#837]
**Idea Description**
The title says everything

**Reference images and links**
<img width="495" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/fd69d6ee-8bfe-427b-a58b-8d3f68f25044">

**Comment by sanao1006** [comment]
Can I take this task?

**Comment by upon0426** [comment]
Sure! Thanks, go ahead!

**Comment by sanao1006** [comment]
Hi! Let me confirm one thing!

It looks like both of the areas where the margins are to be changed are originally 12dp, but how can I check this?
マージンを変更する箇所は両方とももとは12dpのようですが、どのように確認することができるでしょうか？

I was wondering if I could use the "Layout inspector" in Android Studio.
Android Studioの"Layout inspector"を使えばよいかと思って調べました。

As you can see in the image, the Row height is 48dp while the inner elements are 32dp, so I thought the top and bottom margins should both be 8dp.....
すると画像の通り、Rowの高さが48dpに対し内部の要素が32dpなので上下の余白は両方とも8dpなのではと思ったのですが...

It is very possible that I am wrong and I would like to confirm this!
私が調べた方法が間違っている可能性が非常に高いので確認したいです！

<img src="https://github.com/DroidKaigi/conference-app-2023/assets/62137820/d6b5fae5-512f-4783-8925-52a8a4710e35" width="500px">  

<img src="https://github.com/DroidKaigi/conference-app-2023/assets/62137820/eef65810-2167-4cff-bb1b-986586ee2c54" width="500px">

**Comment by sanao1006** [comment]
@upon0426 @takahirom 
Sorry, I don't seem to be able to work on it over the weekend, so can I give it up?
