### ISSUE TITLE
Specify boarder accurately with compose

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#840]
**Idea Description**
Avoid use of "|" and specify the boarder using compose

**Reference images and links**

<img width="230" alt="スクリーンショット 2023-08-21 22 07 36" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/47484ee4-76fa-4b97-8dfb-3474e2df40be">

Implementation Idea:
Solution 1: Use Divider and specify bold etc
Solution 2: Use Box and specify color etc
Please take either way

**Comment by matsumo0922** [comment]
I want to try this issue_
