### ISSUE TITLE
Add license description to About screen

### ISSUE THREAD

**Issue by upon0426** [DroidKaigi/conference-app-2023#842]
**Idea Description**
Please add license description seeing figma

**Reference images and links**

<img width="550" alt="スクリーンショット 2023-08-21 22 23 19" src="https://github.com/DroidKaigi/conference-app-2023/assets/45708639/0fa0ac9f-3a24-4e0e-8e85-158d278d4052">

**Comment by matsuurayuki1219** [comment]
Can I take this issue ?
