### ISSUE TITLE
[iOS] Shrink timetable tab when fullscreen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#872]
## Summary
Now the timetable tab is fixed size even if it is fullscreen.
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56044-40865&mode=design&t=0cTnCk5oseHYYDY7-0

**Comment by fumiyasac** [comment]
🙌 (but, I think it is a little difficult. But I' try it !)
