### ISSUE TITLE
[iOS] Fix the icon and title for stamps tab

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#874]
## Summary
Badges was renamed to Stamps and its tab icon was also updated.
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/a2825372-620d-4cda-aade-8d92867110b2" width="300">

**Comment by Shoryu-Y** [comment]
Hi.
I will update them

**Comment by tkhs0604** [comment]
@Shoryu-Y 
Thank you! Assigned!

**Comment by Shoryu-Y** [comment]
@tkhs0604 
In Android, the selected tab icon is filled.
[figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56147-38777&mode=design&t=gHCVGOI3wM7ix03w-0)

However, iOS is not.
Is my perception correct?

**Comment by Shoryu-Y** [comment]
If so, shouldn't the filled stamp icon be included in iOS?

**Comment by tkhs0604** [comment]
@Shoryu-Y 
Thank you for asking!

I thought that the icon was old (different from the current design) and we need to update it with the new one.
But it looks better for the selected tab to be highlighted as you wrote 👍
If possible, could you use those 2 icons in Figma?

**Comment by Shoryu-Y** [comment]
Thank you for replying!
I will try it!
