### ISSUE TITLE
[iOS] Enable to copy main description on timetable detail screen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#885]
## Summary
Now we cannot select and copy session's main description, so make it selectable.
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/bc2208b9-fd3c-4735-8a6b-54f2d8e582e8" width="300">

**Comment by woxtu** [comment]
🤚

**Comment by mhidaka** [comment]
@woxtu We welcome your contrib! Thanks!
