### ISSUE TITLE
[iOS] Add typography set as a theme

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#889]
## Summary
We need to add typography set into theme module.
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56041-40580&mode=design&t=INXVQMdn5XadnO7e-0

**Comment by Corvus400** [comment]
May I try this task?🙋

**Comment by takahirom** [comment]
Thanks! Assigned 🍎

**Comment by Corvus400** [comment]
@tkhs0604 @takahirom 
Let me check. :bow: 
Does this task mean adding the contents of swiftgen.yml in #1047 to Theme/swifgen.yml?
If so, would merging the contents of #1047 complete this issue?

**Comment by tkhs0604** [comment]
@Corvus400 
This issue intends to define all patterns that we can use in the app for iOS side.
https://github.com/DroidKaigi/conference-app-2023/issues/888 just adds the new font file, but I think it is ok to merge these 2 issues. Of course, we can keep them separated.
If you are interested in this issue too, I would like to assign you 😉

**Comment by tkhs0604** [comment]
Hmm... but some definitions in the above Figma file label `Android + Web`... 🤔

@ry-itto 
Do you know if iOS side will also use these definitions too? 👀

**Comment by Corvus400** [comment]
@tkhs0604 
Understood!
I think #1047 is merged and ready to execute this task, so I'd like to get serious about it.🫡
