### ISSUE TITLE
[iOS] Add radius set as a theme

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#890]
## Summary
We need to add radius set into theme module.
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56618-49877&mode=design&t=INXVQMdn5XadnO7e-0

**Comment by Corvus400** [comment]
I would like to do this task.🙋

**Comment by Corvus400** [comment]
@tkhs0604 @ry-itto 
I have addressed this in #1143
