### ISSUE TITLE
[iOS] Add spacing set as a theme

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#891]
## Summary
We need to add spacing set into theme module.
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56618-49907&mode=design&t=INXVQMdn5XadnO7e-0

**Comment by Corvus400** [comment]
I would like to do this task.🙋

**Comment by ry-itto** [comment]
@Corvus400 
Thank you! Assigned👍
