### ISSUE TITLE
Adding tests to BookmarkScreenTest

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#894]
**Idea Description**
The title says everything.
We might have to use UserDataStore to adjust the bookmark.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/pull/868

**Comment by hiesiea** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by hiesiea** [comment]
> We might have to use UserDataStore to adjust the bookmark.

Sorry, I have a question.
I tried to write a value using UserDataStore#toggleFavorite, but when I debugged it, it didn't seem to be written.

```kotlin
class BookmarkScreenRobot @Inject constructor(
    private val testDispatcher: TestDispatcher,
) {
    ...
    @Inject lateinit var userDataStore: UserDataStore
    ...
    fun toggleFavorite() = runTest(testDispatcher) {
        SessionsAllResponse.fake().toTimetable().bookmarks.forEach {
            userDataStore.toggleFavorite(it)
        }
    }
    ...
}
```

Could you please tell me what I should do?
