### ISSUE TITLE
Adding animations for bookmarks

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#899]
**Idea Description**
Please add the bookmark animation. We have both json and lottie files. Use whichever you prefer. Lottie files are usually smaller.
https://github.com/DroidKaigi/conference-app-2023/tree/main/feature/sessions/src/main/res/raw

**Reference images and links**
- [Figma Light](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=58036-67315)
- [Figma Dark](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=58036-72401)
- [Prototype](https://www.figma.com/proto/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?page-id=56147%3A59334&type=design&node-id=58001-59246&viewport=-1567%2C-1984%2C0.49&t=MvZ3AcVkTw0meYNw-1&scaling=min-zoom&starting-point-node-id=58001%3A59246&show-proto-sidebar=1)

**Comment by Corvus400** [comment]
I can access Lottie, but I don't seem to have access to GoogleDrive!
![image](https://github.com/DroidKaigi/conference-app-2023/assets/13657682/b2c090c0-8609-4f03-babf-4dd7f2368170)

**Comment by Corvus400** [comment]
Can I have this task?

**Comment by momomomo111** [comment]
@Corvus400 
I apologize for the lack of clarity. The files related to Lottie are already in the project at the specified location, so there's no need to access Google Drive.
https://github.com/DroidKaigi/conference-app-2023/tree/main/feature/sessions/src/main/res/raw
