### ISSUE TITLE
Adding animation when stamp is pressed

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#900]
**Idea Description**
Please add an animation when the stamp is pressed.
We have both json and lottie files. Use whichever you prefer. Lottie files are usually smaller.
(For the timing when the stamp is pressed, we currently haven't implemented it. I'd appreciate it if you could set it up so that when a faint-colored animal icon is clicked, the animation runs.)
https://github.com/DroidKaigi/conference-app-2023/tree/main/feature/stamps/src/main/res/raw

**Reference images and links**
- [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55666-94384&mode=dev)

**Comment by momomomo111** [comment]
I apologize, but the Preview is currently unavailable. Instead, please refer to the folder below for implementation.🙏
https://github.com/DroidKaigi/conference-app-2023/tree/main/feature/stamps/src/main/res/raw

**Comment by Corvus400** [comment]
Can I be in charge of this task as well since it seems to be in conflict with the #899  task?

**Comment by Corvus400** [comment]
@momomomo111 
The other task I currently have is waiting for review modification.
I would like to work on this task while I wait. 🙋

**Comment by momomomo111** [comment]
@Corvus400 
Thanks!

**Comment by Corvus400** [comment]
@momomomo111 
I have a question!🙋
Can you tell me the Alpha value of the background color while displaying the stamp?

https://github.com/DroidKaigi/conference-app-2023/assets/13657682/197866a7-46a4-4890-b931-8d80ad497f42

**Comment by Corvus400** [comment]
@momomomo111 
I made a [draft PR](https://github.com/DroidKaigi/conference-app-2023/pull/976)once.
This is how it works at the moment.
Will this Issue also address this part of the Lottie animation after it finishes playing?

Light | Dark
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/5eefba03-8f6d-4b45-95a6-ee169759c8f6" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/116c1ba1-d6d0-4c7b-b86a-9d777feddec8" width="300" >

<img width="708" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/c1fa87fe-3caf-4f31-aef0-7ea9d1642368">

**Comment by Corvus400** [comment]
@momomomo111 
I applied the animation described in Figma to the background color when the stamp animation is playing.
Is this implementation correct?
#976

**Comment by momomomo111** [comment]
@Corvus400 
Thank you for applying!
I think your implementation fully meets the requirements of this Issue.
We are waiting for the designer's confirmation, so please wait a little longer.🙏
