### ISSUE TITLE
No.509 problem again (AS Preview depends on PC language settings)

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2023#902]
**Describe the bug**
As the title says.

**To Reproduce**
MultiLanguagePreviews Check for parts with annotations.

**Expected behavior**
Revert to the status resolved in #509 

**Screenshots**

![image](https://github.com/DroidKaigi/conference-app-2023/assets/13657682/a3dadf21-bec2-4169-9634-d0410b59557e)

**Comment by Corvus400** [comment]
By the way, fixing [this part](https://github.com/DroidKaigi/conference-app-2023/blob/main/core/designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2023/designsystem/preview/Annotations.kt#L52-L69) as shown in the attached image appears to solve the problem.
However, I think this response is probably not correct since the No. 627 response makes it look like this, is that correct?

![image](https://github.com/DroidKaigi/conference-app-2023/assets/13657682/3139a867-373c-4e32-8602-abe7666d2421)
![image](https://github.com/DroidKaigi/conference-app-2023/assets/13657682/394edb62-9731-4c8e-a550-88307b36fffc)

**Comment by takahirom** [comment]
I think this PR is affected by this issue.
We might have to divide the const for test and for preview.
https://github.com/DroidKaigi/conference-app-2023/pull/809

**Comment by ked4ma** [comment]
I'll divide these locale string :raised_back_of_hand:
