### ISSUE TITLE
Set JST Timezone for tests

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#906]
**Idea Description**
We might have it to RobotTest

**Reference images and links**

This should be 10:30 am

<img width="783" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/afcff285-d147-41a4-832e-07ebfcae68a4">

**Comment by chibatching** [comment]
I'll try this! 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
