### ISSUE TITLE
Find a normal session for TimetableItemDetailScreenTest

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#915]
**Idea Description**
In this PR, we are having welcome session in screenshots. However, I would like to see the normal session screenshots.
So could we do `SessionsAllResponse.fake().sessions.first{ it.xxxxType == Normal }.id  ` or something to find the normal session?
https://github.com/DroidKaigi/conference-app-2023/pull/822
<img width="829" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/81c9c481-9291-49e7-acd7-b0f8488ce886">

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/blob/39f785294d84e6e44017f6160e2e4438e80ab923/core/testing/src/main/java/io/github/droidkaigi/confsched2023/testing/robot/TimetableItemDetailScreenRobot.kt#L93

**Comment by shinya-takano** [comment]
can i do this? 🤚 already create PR
