### ISSUE TITLE
[iOS] Support large size screen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#924]
**Idea Description**

- Currently, this iOS app supports only mobile style design. Please support large size screen as well 🙏🏼 
- [NavigationSplitView](https://developer.apple.com/documentation/swiftui/navigationsplitview) may be useful for large screen navigation 🙏🏼 

**Reference images and links**

- https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=57938-75677&mode=dev

**Comment by coe** [comment]
🙋
