### ISSUE TITLE
[iOS] Add highlight for searchWord in SearchView

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#925]
**Idea Description**

- Currently, no UI changes for session titles when user input searchWord. Please reflect searchWord to sessionTitle with highlighted effect.

**Reference images and links**

- https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=58036-78603&mode=dev

**Comment by fumiyasac** [comment]
🖐️

**Comment by mhidaka** [comment]
@fumiyasac Thanks for your comment, please go ahead!

**Comment by fumiyasac** [comment]
@mhidaka 
Thanks. I already send pull request about this issue.
I hope I'll merge it. 😍
