### ISSUE TITLE
[iOS] Create License Package and execute prepare plugin with appropriate way

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2023#926]
**Idea Description**

- Currently, `LicenseView` is defined in `About` package and prepare plist command is executed in Xcode Build Phase. Please improve this behavior with appropriate way. (For example, execute prepare plist command with SPM Plugin.)

**Reference images and links**

- https://github.com/DroidKaigi/conference-app-2023/pull/878#pullrequestreview-1589900452

**Comment by swiftty** [comment]
🙋

**Comment by ry-itto** [comment]
@swiftty 
Thanks! Assigned 👍🏼
