### ISSUE TITLE
[Android] App crashes on Contributors tab if the API token is expired

### ISSUE THREAD

**Issue by Noddy20** [DroidKaigi/conference-app-2023#950]
**Bug description**
App crashed on Contributors tab when the API token was expired and the response was not containing the contributors list.
Might be an edge case to reproduce, since it happened in an emulator where the was kept open for a long time.

**API response**
`401` https://ssot-api-staging.an.r.appspot.com//events/droidkaigi2023/contributors
`{"status":"UNAUTHORIZED","summary":"The token has been expired","code":401001,"errors":[]}`

**To Reproduce**
1. Keep app open to let the API token expire
2. switch to Contributors tab
3. App will crash

**Expected behavior**
App should not crash, and instead show some error

**Crash Stacktrace**
`io.github.droidkaigi.confsched2023.model.AppError$UnknownException: io.ktor.serialization.JsonConvertException: Illegal input: Field 'contributors' is required for type with serial name 'io.github.droidkaigi.confsched2023.data.contributors.response.ContributorsResponse', but it was missing at path: $`

**Comment by Noddy20** [comment]
Adding default value (`emptyList()`) for the `contributors` variable in the `ContributorsResponse` data class can fix the issue.

`core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/data/contributors/response/ContributorsResponse.kt`

**Comment by takahirom** [comment]
We can fix it temporarily using emptyList() or something but I think catching it may be a good solution for now.
I think the ideal solution is `handleAndErrorRetry` but it seems difficult.
https://github.com/DroidKaigi/conference-app-2023/issues/752

**Comment by tkhs0604** [comment]
This issue might be resolved by https://github.com/DroidKaigi/conference-app-2023/pull/1016.

**Comment by tkhs0604** [comment]
This issue might be resolved by https://github.com/DroidKaigi/conference-app-2023/pull/1016 👀

**Comment by takahirom** [comment]
Thanks! It could be the different issue
