### ISSUE TITLE
Ripple at the top of TimetableListItem is cut off.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#960]
**Idea Description**
Sorry if this is unnecessary.

Top of Ripple is cut off when tapping `TimetableListItem` used in 3 screens `BookmarkList`, `SearchList`, `TimetableList`.

Personally, I would have preferred to see Ripple up to Divider when I tapped TimetableListItem.

**Reference images and links**
|list|picture|
|---|---|
|BookmarkList|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/6acc0e3d-d8c3-4b59-94ff-f70059e5cf24" width="300">|
|SearchList|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/7fc94a27-d139-4902-b781-5d7bd2e3c05f" width="300">|
|TimetableList|<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/7eb6dac2-e398-431d-b0d1-125de90022b7" width="300">|

**Comment by kosenda** [comment]
I'd like to try ！

**Comment by RyuNen344** [comment]
@kosenda 
sorry for late 🙇  asssigned!

**Comment by kosenda** [comment]
Thank you for your time !!
