### ISSUE TITLE
Bookmarking with `TimetableItemDetail` automatically shrinks the `DescriptionSection`

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#967]
**Describe the bug**
When `ReadMoreOutlinedButton` is pressed in `TimetableItemDetail` and the DescriptionSection is expanded, pressing the bottom bookmark will automatically shrink `DescriptionSection`.

**To Reproduce**
1. Go to `TimetableItemDetail`
2. Click on `ReadMoreOutlinedButton`
3. Click on BookmarkIcon

**Expected behavior**
`DescriptionSection` does not shrink when Bookmark is pressed

**Screenshots**
Emulator(Pixel4 API28)

https://github.com/DroidKaigi/conference-app-2023/assets/60963155/8c03e1ad-0c96-4a54-b6e7-1dcc187cc523

**Comment by takahirom** [comment]
It's strange. I wonder why..  👀

**Comment by iiinaiii** [comment]
I would like to try this issue🙋‍♂️

**Comment by momomomo111** [comment]
@iiinaiii 
Thanks! Assigned!
