### ISSUE TITLE
The TimetableItemDetail Snackbar doesn't disappear after some seconds

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#969]
**Idea Description**
Sorry if this is unnecessary.

`SpeakerSection` is hidden by snackbar when `TimetableItemDetail` Bookmark is pressed, I thought it would be better to display space for snackbar when snackbar is show so that the `SpeakerSection` is not hidden.

I think I can detect `SnackbarHostState` and create space by doing a bucket relay or using `CompositionLocalProvider`.

**Reference images and links**
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/d50ff2f7-efa2-4295-8986-c305da2190f3" width="300">

**Comment by takahirom** [comment]
I think the problem is that The bookmark screen Snackbar doesn't disappear after some seconds.

**Comment by kosenda** [comment]
I would like to work this issue !

My question, is `SnackbarDuration.Short (4s)` the right time to delete snackbar?

**Comment by takahirom** [comment]
I think so!

**Comment by kosenda** [comment]
Thank you !
I would like to get started, so would it be possible for me to be assign?

**Comment by mhidaka** [comment]
@kosenda Sure, We assign you! 😊

**Comment by kosenda** [comment]
@mhidaka Thank you for assigning me 🙇
