### ISSUE TITLE
Consecutive presses of back button on  screen cause a transition to  blank screen

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2023#971]
**Describe the bug**
When I consective presses back button repeatedly on the following screen, transition to blank screen.
- `SearchScreen` 
- `TimetableItemDetailScreen`
- `StaffScreen`
- `SponsorsScreen`

**To Reproduce**
1. Go to Screens enumerated above
2. Consecutive click on back button

**Expected behavior**
No matter how many times I press back button, it does not to transition screen.

**Screenshots**
|SearchScreen|TimetableItemDetailScreen|StaffScreen|SponsorsScreen|
|---|---|---|---|
|<video src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/1be0bc0b-5eae-4938-9753-49ae6bd80c5b" width="300">|<video src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/57f480be-a201-497b-91ae-8f9cc6dba1cf" width="300">|<video src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/a3d9b1ec-104a-4f7b-9a86-1160910d77cd" width="300">|<video src="https://github.com/DroidKaigi/conference-app-2023/assets/60963155/958aca72-10f9-4a62-8ee9-a813cb515b07" width="300">|

## **Related issue**
https://github.com/DroidKaigi/conference-app-2023/issues/468

This issue has been corrected as follows
https://github.com/DroidKaigi/conference-app-2023/blob/99a14d95be8c98e7190862115e39935491928c1f/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkTopArea.kt#L128-L134

**Comment by takahirom** [comment]
Thanks for this issue! Maybe we have to create a utility method for it.

**Comment by ked4ma** [comment]
I wanna try ! :raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
Thanks as always!
