### ISSUE TITLE
Rename stamps and badges to achievements

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2023#984]
**Idea Description**
The sections previously referred to as `stamps` and `badges` have caused a conflict with other terminology used in DroidKaigi.
As a result, we have decided to rename them to `achievement`.
Please update all functions, module names, and areas where the terms `stamp`, `stamps`, `Badge`, and `Badges` are used to `achievement` or `achievements`

**Reference images and links**
![スクリーンショット 2023-08-27 午後5 25 53](https://github.com/DroidKaigi/conference-app-2023/assets/51113946/445c59eb-2ce2-4cc7-a135-25d5081d5b9d)

**Comment by r4wxii** [comment]
🙋‍♀️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
